// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/firebasealerts/v1/cloud_event_payload.proto

package google.events.firebase.firebasealerts.v1;

/**
 * Protobuf type {@code google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload}
 */
public final class FireperfThresholdAlertPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload)
    FireperfThresholdAlertPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FireperfThresholdAlertPayload.newBuilder() to construct.
  private FireperfThresholdAlertPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FireperfThresholdAlertPayload() {
    eventName_ = "";
    eventType_ = "";
    metricType_ = "";
    thresholdUnit_ = "";
    appVersion_ = "";
    violationUnit_ = "";
    investigateUri_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FireperfThresholdAlertPayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.events.firebase.firebasealerts.v1.CloudEventPayload.internal_static_google_events_firebase_firebasealerts_v1_FireperfThresholdAlertPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.events.firebase.firebasealerts.v1.CloudEventPayload.internal_static_google_events_firebase_firebasealerts_v1_FireperfThresholdAlertPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.class, google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.Builder.class);
  }

  public static final int EVENT_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object eventName_;
  /**
   * <pre>
   * Name of the trace or network request this alert is for (e.g.
   * my_custom_trace, firebase.com/api/123)
   * </pre>
   *
   * <code>string event_name = 1;</code>
   * @return The eventName.
   */
  @java.lang.Override
  public java.lang.String getEventName() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the trace or network request this alert is for (e.g.
   * my_custom_trace, firebase.com/api/123)
   * </pre>
   *
   * <code>string event_name = 1;</code>
   * @return The bytes for eventName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventNameBytes() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object eventType_;
  /**
   * <pre>
   * The resource type this alert is for (i.e. trace, network request, screen
   * rendering, etc.)
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The resource type this alert is for (i.e. trace, network request, screen
   * rendering, etc.)
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRIC_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object metricType_;
  /**
   * <pre>
   * The metric type this alert is for (i.e. success rate, response time,
   * duration, etc.)
   * </pre>
   *
   * <code>string metric_type = 3;</code>
   * @return The metricType.
   */
  @java.lang.Override
  public java.lang.String getMetricType() {
    java.lang.Object ref = metricType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metricType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The metric type this alert is for (i.e. success rate, response time,
   * duration, etc.)
   * </pre>
   *
   * <code>string metric_type = 3;</code>
   * @return The bytes for metricType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetricTypeBytes() {
    java.lang.Object ref = metricType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metricType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_SAMPLES_FIELD_NUMBER = 4;
  private long numSamples_;
  /**
   * <pre>
   * The number of events checked for this alert condition
   * </pre>
   *
   * <code>int64 num_samples = 4;</code>
   * @return The numSamples.
   */
  @java.lang.Override
  public long getNumSamples() {
    return numSamples_;
  }

  public static final int THRESHOLD_VALUE_FIELD_NUMBER = 5;
  private float thresholdValue_;
  /**
   * <pre>
   * The threshold value of the alert condition without units (e.g. "75", "2.1")
   * </pre>
   *
   * <code>float threshold_value = 5;</code>
   * @return The thresholdValue.
   */
  @java.lang.Override
  public float getThresholdValue() {
    return thresholdValue_;
  }

  public static final int THRESHOLD_UNIT_FIELD_NUMBER = 6;
  private volatile java.lang.Object thresholdUnit_;
  /**
   * <pre>
   * The unit for the alert threshold (e.g. "percent", "seconds")
   * </pre>
   *
   * <code>string threshold_unit = 6;</code>
   * @return The thresholdUnit.
   */
  @java.lang.Override
  public java.lang.String getThresholdUnit() {
    java.lang.Object ref = thresholdUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      thresholdUnit_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unit for the alert threshold (e.g. "percent", "seconds")
   * </pre>
   *
   * <code>string threshold_unit = 6;</code>
   * @return The bytes for thresholdUnit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThresholdUnitBytes() {
    java.lang.Object ref = thresholdUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      thresholdUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONDITION_PERCENTILE_FIELD_NUMBER = 7;
  private int conditionPercentile_;
  /**
   * <pre>
   * The percentile of the alert condition, can be 0 if percentile is not
   * applicable to the alert condition; range: [0, 100]
   * </pre>
   *
   * <code>int32 condition_percentile = 7;</code>
   * @return The conditionPercentile.
   */
  @java.lang.Override
  public int getConditionPercentile() {
    return conditionPercentile_;
  }

  public static final int APP_VERSION_FIELD_NUMBER = 8;
  private volatile java.lang.Object appVersion_;
  /**
   * <pre>
   * The app version this alert was triggered for, can be empty if the alert is
   * for a network request (because the alert was checked against data from all
   * versions of app) or a web app (where the app is versionless)
   * </pre>
   *
   * <code>string app_version = 8;</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public java.lang.String getAppVersion() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The app version this alert was triggered for, can be empty if the alert is
   * for a network request (because the alert was checked against data from all
   * versions of app) or a web app (where the app is versionless)
   * </pre>
   *
   * <code>string app_version = 8;</code>
   * @return The bytes for appVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionBytes() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIOLATION_VALUE_FIELD_NUMBER = 9;
  private float violationValue_;
  /**
   * <pre>
   * The value that violated the alert condition (e.g. "76.5", "3")
   * </pre>
   *
   * <code>float violation_value = 9;</code>
   * @return The violationValue.
   */
  @java.lang.Override
  public float getViolationValue() {
    return violationValue_;
  }

  public static final int VIOLATION_UNIT_FIELD_NUMBER = 10;
  private volatile java.lang.Object violationUnit_;
  /**
   * <pre>
   * The unit for the violation value (e.g. "percent", "seconds")
   * </pre>
   *
   * <code>string violation_unit = 10;</code>
   * @return The violationUnit.
   */
  @java.lang.Override
  public java.lang.String getViolationUnit() {
    java.lang.Object ref = violationUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      violationUnit_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unit for the violation value (e.g. "percent", "seconds")
   * </pre>
   *
   * <code>string violation_unit = 10;</code>
   * @return The bytes for violationUnit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getViolationUnitBytes() {
    java.lang.Object ref = violationUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      violationUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVESTIGATE_URI_FIELD_NUMBER = 11;
  private volatile java.lang.Object investigateUri_;
  /**
   * <pre>
   * The link to Fireconsole to investigate more into this alert
   * </pre>
   *
   * <code>string investigate_uri = 11;</code>
   * @return The investigateUri.
   */
  @java.lang.Override
  public java.lang.String getInvestigateUri() {
    java.lang.Object ref = investigateUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      investigateUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The link to Fireconsole to investigate more into this alert
   * </pre>
   *
   * <code>string investigate_uri = 11;</code>
   * @return The bytes for investigateUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvestigateUriBytes() {
    java.lang.Object ref = investigateUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      investigateUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(metricType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, metricType_);
    }
    if (numSamples_ != 0L) {
      output.writeInt64(4, numSamples_);
    }
    if (java.lang.Float.floatToRawIntBits(thresholdValue_) != 0) {
      output.writeFloat(5, thresholdValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(thresholdUnit_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, thresholdUnit_);
    }
    if (conditionPercentile_ != 0) {
      output.writeInt32(7, conditionPercentile_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, appVersion_);
    }
    if (java.lang.Float.floatToRawIntBits(violationValue_) != 0) {
      output.writeFloat(9, violationValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(violationUnit_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, violationUnit_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(investigateUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, investigateUri_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(metricType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, metricType_);
    }
    if (numSamples_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, numSamples_);
    }
    if (java.lang.Float.floatToRawIntBits(thresholdValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, thresholdValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(thresholdUnit_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, thresholdUnit_);
    }
    if (conditionPercentile_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, conditionPercentile_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, appVersion_);
    }
    if (java.lang.Float.floatToRawIntBits(violationValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(9, violationValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(violationUnit_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, violationUnit_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(investigateUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, investigateUri_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload)) {
      return super.equals(obj);
    }
    google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload other = (google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload) obj;

    if (!getEventName()
        .equals(other.getEventName())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getMetricType()
        .equals(other.getMetricType())) return false;
    if (getNumSamples()
        != other.getNumSamples()) return false;
    if (java.lang.Float.floatToIntBits(getThresholdValue())
        != java.lang.Float.floatToIntBits(
            other.getThresholdValue())) return false;
    if (!getThresholdUnit()
        .equals(other.getThresholdUnit())) return false;
    if (getConditionPercentile()
        != other.getConditionPercentile()) return false;
    if (!getAppVersion()
        .equals(other.getAppVersion())) return false;
    if (java.lang.Float.floatToIntBits(getViolationValue())
        != java.lang.Float.floatToIntBits(
            other.getViolationValue())) return false;
    if (!getViolationUnit()
        .equals(other.getViolationUnit())) return false;
    if (!getInvestigateUri()
        .equals(other.getInvestigateUri())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEventName().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + METRIC_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMetricType().hashCode();
    hash = (37 * hash) + NUM_SAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumSamples());
    hash = (37 * hash) + THRESHOLD_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getThresholdValue());
    hash = (37 * hash) + THRESHOLD_UNIT_FIELD_NUMBER;
    hash = (53 * hash) + getThresholdUnit().hashCode();
    hash = (37 * hash) + CONDITION_PERCENTILE_FIELD_NUMBER;
    hash = (53 * hash) + getConditionPercentile();
    hash = (37 * hash) + APP_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAppVersion().hashCode();
    hash = (37 * hash) + VIOLATION_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getViolationValue());
    hash = (37 * hash) + VIOLATION_UNIT_FIELD_NUMBER;
    hash = (53 * hash) + getViolationUnit().hashCode();
    hash = (37 * hash) + INVESTIGATE_URI_FIELD_NUMBER;
    hash = (53 * hash) + getInvestigateUri().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload)
      google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.events.firebase.firebasealerts.v1.CloudEventPayload.internal_static_google_events_firebase_firebasealerts_v1_FireperfThresholdAlertPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.events.firebase.firebasealerts.v1.CloudEventPayload.internal_static_google_events_firebase_firebasealerts_v1_FireperfThresholdAlertPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.class, google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.Builder.class);
    }

    // Construct using google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventName_ = "";

      eventType_ = "";

      metricType_ = "";

      numSamples_ = 0L;

      thresholdValue_ = 0F;

      thresholdUnit_ = "";

      conditionPercentile_ = 0;

      appVersion_ = "";

      violationValue_ = 0F;

      violationUnit_ = "";

      investigateUri_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.events.firebase.firebasealerts.v1.CloudEventPayload.internal_static_google_events_firebase_firebasealerts_v1_FireperfThresholdAlertPayload_descriptor;
    }

    @java.lang.Override
    public google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload getDefaultInstanceForType() {
      return google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.getDefaultInstance();
    }

    @java.lang.Override
    public google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload build() {
      google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload buildPartial() {
      google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload result = new google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload(this);
      result.eventName_ = eventName_;
      result.eventType_ = eventType_;
      result.metricType_ = metricType_;
      result.numSamples_ = numSamples_;
      result.thresholdValue_ = thresholdValue_;
      result.thresholdUnit_ = thresholdUnit_;
      result.conditionPercentile_ = conditionPercentile_;
      result.appVersion_ = appVersion_;
      result.violationValue_ = violationValue_;
      result.violationUnit_ = violationUnit_;
      result.investigateUri_ = investigateUri_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload) {
        return mergeFrom((google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload other) {
      if (other == google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload.getDefaultInstance()) return this;
      if (!other.getEventName().isEmpty()) {
        eventName_ = other.eventName_;
        onChanged();
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        onChanged();
      }
      if (!other.getMetricType().isEmpty()) {
        metricType_ = other.metricType_;
        onChanged();
      }
      if (other.getNumSamples() != 0L) {
        setNumSamples(other.getNumSamples());
      }
      if (other.getThresholdValue() != 0F) {
        setThresholdValue(other.getThresholdValue());
      }
      if (!other.getThresholdUnit().isEmpty()) {
        thresholdUnit_ = other.thresholdUnit_;
        onChanged();
      }
      if (other.getConditionPercentile() != 0) {
        setConditionPercentile(other.getConditionPercentile());
      }
      if (!other.getAppVersion().isEmpty()) {
        appVersion_ = other.appVersion_;
        onChanged();
      }
      if (other.getViolationValue() != 0F) {
        setViolationValue(other.getViolationValue());
      }
      if (!other.getViolationUnit().isEmpty()) {
        violationUnit_ = other.violationUnit_;
        onChanged();
      }
      if (!other.getInvestigateUri().isEmpty()) {
        investigateUri_ = other.investigateUri_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              eventType_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              metricType_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 32: {
              numSamples_ = input.readInt64();

              break;
            } // case 32
            case 45: {
              thresholdValue_ = input.readFloat();

              break;
            } // case 45
            case 50: {
              thresholdUnit_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 56: {
              conditionPercentile_ = input.readInt32();

              break;
            } // case 56
            case 66: {
              appVersion_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 77: {
              violationValue_ = input.readFloat();

              break;
            } // case 77
            case 82: {
              violationUnit_ = input.readStringRequireUtf8();

              break;
            } // case 82
            case 90: {
              investigateUri_ = input.readStringRequireUtf8();

              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object eventName_ = "";
    /**
     * <pre>
     * Name of the trace or network request this alert is for (e.g.
     * my_custom_trace, firebase.com/api/123)
     * </pre>
     *
     * <code>string event_name = 1;</code>
     * @return The eventName.
     */
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the trace or network request this alert is for (e.g.
     * my_custom_trace, firebase.com/api/123)
     * </pre>
     *
     * <code>string event_name = 1;</code>
     * @return The bytes for eventName.
     */
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the trace or network request this alert is for (e.g.
     * my_custom_trace, firebase.com/api/123)
     * </pre>
     *
     * <code>string event_name = 1;</code>
     * @param value The eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the trace or network request this alert is for (e.g.
     * my_custom_trace, firebase.com/api/123)
     * </pre>
     *
     * <code>string event_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventName() {
      
      eventName_ = getDefaultInstance().getEventName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the trace or network request this alert is for (e.g.
     * my_custom_trace, firebase.com/api/123)
     * </pre>
     *
     * <code>string event_name = 1;</code>
     * @param value The bytes for eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <pre>
     * The resource type this alert is for (i.e. trace, network request, screen
     * rendering, etc.)
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The resource type this alert is for (i.e. trace, network request, screen
     * rendering, etc.)
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The resource type this alert is for (i.e. trace, network request, screen
     * rendering, etc.)
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource type this alert is for (i.e. trace, network request, screen
     * rendering, etc.)
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      
      eventType_ = getDefaultInstance().getEventType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource type this alert is for (i.e. trace, network request, screen
     * rendering, etc.)
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object metricType_ = "";
    /**
     * <pre>
     * The metric type this alert is for (i.e. success rate, response time,
     * duration, etc.)
     * </pre>
     *
     * <code>string metric_type = 3;</code>
     * @return The metricType.
     */
    public java.lang.String getMetricType() {
      java.lang.Object ref = metricType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The metric type this alert is for (i.e. success rate, response time,
     * duration, etc.)
     * </pre>
     *
     * <code>string metric_type = 3;</code>
     * @return The bytes for metricType.
     */
    public com.google.protobuf.ByteString
        getMetricTypeBytes() {
      java.lang.Object ref = metricType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The metric type this alert is for (i.e. success rate, response time,
     * duration, etc.)
     * </pre>
     *
     * <code>string metric_type = 3;</code>
     * @param value The metricType to set.
     * @return This builder for chaining.
     */
    public Builder setMetricType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metricType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The metric type this alert is for (i.e. success rate, response time,
     * duration, etc.)
     * </pre>
     *
     * <code>string metric_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricType() {
      
      metricType_ = getDefaultInstance().getMetricType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The metric type this alert is for (i.e. success rate, response time,
     * duration, etc.)
     * </pre>
     *
     * <code>string metric_type = 3;</code>
     * @param value The bytes for metricType to set.
     * @return This builder for chaining.
     */
    public Builder setMetricTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metricType_ = value;
      onChanged();
      return this;
    }

    private long numSamples_ ;
    /**
     * <pre>
     * The number of events checked for this alert condition
     * </pre>
     *
     * <code>int64 num_samples = 4;</code>
     * @return The numSamples.
     */
    @java.lang.Override
    public long getNumSamples() {
      return numSamples_;
    }
    /**
     * <pre>
     * The number of events checked for this alert condition
     * </pre>
     *
     * <code>int64 num_samples = 4;</code>
     * @param value The numSamples to set.
     * @return This builder for chaining.
     */
    public Builder setNumSamples(long value) {
      
      numSamples_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of events checked for this alert condition
     * </pre>
     *
     * <code>int64 num_samples = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumSamples() {
      
      numSamples_ = 0L;
      onChanged();
      return this;
    }

    private float thresholdValue_ ;
    /**
     * <pre>
     * The threshold value of the alert condition without units (e.g. "75", "2.1")
     * </pre>
     *
     * <code>float threshold_value = 5;</code>
     * @return The thresholdValue.
     */
    @java.lang.Override
    public float getThresholdValue() {
      return thresholdValue_;
    }
    /**
     * <pre>
     * The threshold value of the alert condition without units (e.g. "75", "2.1")
     * </pre>
     *
     * <code>float threshold_value = 5;</code>
     * @param value The thresholdValue to set.
     * @return This builder for chaining.
     */
    public Builder setThresholdValue(float value) {
      
      thresholdValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The threshold value of the alert condition without units (e.g. "75", "2.1")
     * </pre>
     *
     * <code>float threshold_value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearThresholdValue() {
      
      thresholdValue_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object thresholdUnit_ = "";
    /**
     * <pre>
     * The unit for the alert threshold (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string threshold_unit = 6;</code>
     * @return The thresholdUnit.
     */
    public java.lang.String getThresholdUnit() {
      java.lang.Object ref = thresholdUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        thresholdUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unit for the alert threshold (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string threshold_unit = 6;</code>
     * @return The bytes for thresholdUnit.
     */
    public com.google.protobuf.ByteString
        getThresholdUnitBytes() {
      java.lang.Object ref = thresholdUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thresholdUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unit for the alert threshold (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string threshold_unit = 6;</code>
     * @param value The thresholdUnit to set.
     * @return This builder for chaining.
     */
    public Builder setThresholdUnit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      thresholdUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unit for the alert threshold (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string threshold_unit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearThresholdUnit() {
      
      thresholdUnit_ = getDefaultInstance().getThresholdUnit();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unit for the alert threshold (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string threshold_unit = 6;</code>
     * @param value The bytes for thresholdUnit to set.
     * @return This builder for chaining.
     */
    public Builder setThresholdUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      thresholdUnit_ = value;
      onChanged();
      return this;
    }

    private int conditionPercentile_ ;
    /**
     * <pre>
     * The percentile of the alert condition, can be 0 if percentile is not
     * applicable to the alert condition; range: [0, 100]
     * </pre>
     *
     * <code>int32 condition_percentile = 7;</code>
     * @return The conditionPercentile.
     */
    @java.lang.Override
    public int getConditionPercentile() {
      return conditionPercentile_;
    }
    /**
     * <pre>
     * The percentile of the alert condition, can be 0 if percentile is not
     * applicable to the alert condition; range: [0, 100]
     * </pre>
     *
     * <code>int32 condition_percentile = 7;</code>
     * @param value The conditionPercentile to set.
     * @return This builder for chaining.
     */
    public Builder setConditionPercentile(int value) {
      
      conditionPercentile_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The percentile of the alert condition, can be 0 if percentile is not
     * applicable to the alert condition; range: [0, 100]
     * </pre>
     *
     * <code>int32 condition_percentile = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearConditionPercentile() {
      
      conditionPercentile_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object appVersion_ = "";
    /**
     * <pre>
     * The app version this alert was triggered for, can be empty if the alert is
     * for a network request (because the alert was checked against data from all
     * versions of app) or a web app (where the app is versionless)
     * </pre>
     *
     * <code>string app_version = 8;</code>
     * @return The appVersion.
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The app version this alert was triggered for, can be empty if the alert is
     * for a network request (because the alert was checked against data from all
     * versions of app) or a web app (where the app is versionless)
     * </pre>
     *
     * <code>string app_version = 8;</code>
     * @return The bytes for appVersion.
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The app version this alert was triggered for, can be empty if the alert is
     * for a network request (because the alert was checked against data from all
     * versions of app) or a web app (where the app is versionless)
     * </pre>
     *
     * <code>string app_version = 8;</code>
     * @param value The appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The app version this alert was triggered for, can be empty if the alert is
     * for a network request (because the alert was checked against data from all
     * versions of app) or a web app (where the app is versionless)
     * </pre>
     *
     * <code>string app_version = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersion() {
      
      appVersion_ = getDefaultInstance().getAppVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The app version this alert was triggered for, can be empty if the alert is
     * for a network request (because the alert was checked against data from all
     * versions of app) or a web app (where the app is versionless)
     * </pre>
     *
     * <code>string app_version = 8;</code>
     * @param value The bytes for appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appVersion_ = value;
      onChanged();
      return this;
    }

    private float violationValue_ ;
    /**
     * <pre>
     * The value that violated the alert condition (e.g. "76.5", "3")
     * </pre>
     *
     * <code>float violation_value = 9;</code>
     * @return The violationValue.
     */
    @java.lang.Override
    public float getViolationValue() {
      return violationValue_;
    }
    /**
     * <pre>
     * The value that violated the alert condition (e.g. "76.5", "3")
     * </pre>
     *
     * <code>float violation_value = 9;</code>
     * @param value The violationValue to set.
     * @return This builder for chaining.
     */
    public Builder setViolationValue(float value) {
      
      violationValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The value that violated the alert condition (e.g. "76.5", "3")
     * </pre>
     *
     * <code>float violation_value = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearViolationValue() {
      
      violationValue_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object violationUnit_ = "";
    /**
     * <pre>
     * The unit for the violation value (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string violation_unit = 10;</code>
     * @return The violationUnit.
     */
    public java.lang.String getViolationUnit() {
      java.lang.Object ref = violationUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        violationUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unit for the violation value (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string violation_unit = 10;</code>
     * @return The bytes for violationUnit.
     */
    public com.google.protobuf.ByteString
        getViolationUnitBytes() {
      java.lang.Object ref = violationUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        violationUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unit for the violation value (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string violation_unit = 10;</code>
     * @param value The violationUnit to set.
     * @return This builder for chaining.
     */
    public Builder setViolationUnit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      violationUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unit for the violation value (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string violation_unit = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearViolationUnit() {
      
      violationUnit_ = getDefaultInstance().getViolationUnit();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unit for the violation value (e.g. "percent", "seconds")
     * </pre>
     *
     * <code>string violation_unit = 10;</code>
     * @param value The bytes for violationUnit to set.
     * @return This builder for chaining.
     */
    public Builder setViolationUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      violationUnit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object investigateUri_ = "";
    /**
     * <pre>
     * The link to Fireconsole to investigate more into this alert
     * </pre>
     *
     * <code>string investigate_uri = 11;</code>
     * @return The investigateUri.
     */
    public java.lang.String getInvestigateUri() {
      java.lang.Object ref = investigateUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        investigateUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The link to Fireconsole to investigate more into this alert
     * </pre>
     *
     * <code>string investigate_uri = 11;</code>
     * @return The bytes for investigateUri.
     */
    public com.google.protobuf.ByteString
        getInvestigateUriBytes() {
      java.lang.Object ref = investigateUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        investigateUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The link to Fireconsole to investigate more into this alert
     * </pre>
     *
     * <code>string investigate_uri = 11;</code>
     * @param value The investigateUri to set.
     * @return This builder for chaining.
     */
    public Builder setInvestigateUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      investigateUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The link to Fireconsole to investigate more into this alert
     * </pre>
     *
     * <code>string investigate_uri = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvestigateUri() {
      
      investigateUri_ = getDefaultInstance().getInvestigateUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The link to Fireconsole to investigate more into this alert
     * </pre>
     *
     * <code>string investigate_uri = 11;</code>
     * @param value The bytes for investigateUri to set.
     * @return This builder for chaining.
     */
    public Builder setInvestigateUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      investigateUri_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload)
  }

  // @@protoc_insertion_point(class_scope:google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload)
  private static final google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload();
  }

  public static google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FireperfThresholdAlertPayload>
      PARSER = new com.google.protobuf.AbstractParser<FireperfThresholdAlertPayload>() {
    @java.lang.Override
    public FireperfThresholdAlertPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FireperfThresholdAlertPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FireperfThresholdAlertPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

