|- LogEntryData(log_name: STRING, resource: MonitoredResource, proto_payload: AuditLog, insert_id: STRING, labels: List<LabelsEntry>, operation: LogEntryOperation, timestamp: Timestamp, receive_timestamp: Timestamp, severity: ENUM, trace: STRING, span_id: STRING, split: LogSplit)
   |- LabelsEntry(key: STRING, value: STRING)
   |- LogEntryOperation(id: STRING, producer: STRING, first: BOOL, last: BOOL)
|- AuditLog(service_name: STRING, method_name: STRING, resource_name: STRING, resource_location: ResourceLocation, resource_original_state: Struct, num_response_items: INT64, status: Status, authentication_info: AuthenticationInfo, authorization_info: List<AuthorizationInfo>, request_metadata: RequestMetadata, request: Struct, response: Struct, metadata: Struct, service_data: Struct)
|- AuthenticationInfo(principal_email: STRING, authority_selector: STRING, third_party_principal: Struct, service_account_key_name: STRING, service_account_delegation_info: List<ServiceAccountDelegationInfo>, principal_subject: STRING)
|- AuthorizationInfo(resource: STRING, permission: STRING, granted: BOOL, resource_attributes: Resource)
|- RequestMetadata(caller_ip: STRING, caller_supplied_user_agent: STRING, caller_network: STRING, request_attributes: Request, destination_attributes: Peer)
|- ResourceLocation(current_locations: List<STRING>, original_locations: List<STRING>)
|- ServiceAccountDelegationInfo(first_party_principal: FirstPartyPrincipal, third_party_principal: ThirdPartyPrincipal)
   |- FirstPartyPrincipal(principal_email: STRING, service_metadata: Struct)
      |- ThirdPartyPrincipal(third_party_claims: Struct)
   |- LogSplit(uid: STRING, index: INT32, total_splits: INT32)
