|- AnalyticsLogData(user_dim: UserDimensions, event_dim: List<EventDimensions>)
|- UserDimensions(user_id: STRING, first_open_timestamp_micros: INT64, user_properties: List<UserPropertiesEntry>, device_info: DeviceInfo, geo_info: GeoInfo, app_info: AppInfo, traffic_source: TrafficSource, bundle_info: ExportBundleInfo, ltv_info: LtvInfo)
   |- UserPropertiesEntry(key: STRING, value: UserPropertyValue)
   |- UserPropertyValue(value: AnalyticsValue, set_timestamp_usec: INT64, index: INT32)
|- AnalyticsValue(string_value: STRING, int_value: INT64, float_value: FLOAT, double_value: DOUBLE)
|- DeviceInfo(device_category: STRING, mobile_brand_name: STRING, mobile_model_name: STRING, mobile_marketing_name: STRING, device_model: STRING, platform_version: STRING, device_id: STRING, resettable_device_id: STRING, user_default_language: STRING, device_time_zone_offset_seconds: INT32, limited_ad_tracking: BOOL)
|- AppInfo(app_version: STRING, app_instance_id: STRING, app_store: STRING, app_platform: STRING, app_id: STRING)
|- GeoInfo(continent: STRING, country: STRING, region: STRING, city: STRING)
|- TrafficSource(user_acquired_campaign: STRING, user_acquired_source: STRING, user_acquired_medium: STRING)
|- ExportBundleInfo(bundle_sequence_id: INT32, server_timestamp_offset_micros: INT64)
|- LtvInfo(revenue: DOUBLE, currency: STRING)
|- EventDimensions(date: STRING, name: STRING, params: List<ParamsEntry>, timestamp_micros: INT64, previous_timestamp_micros: INT64, value_in_usd: DOUBLE)
   |- ParamsEntry(key: STRING, value: AnalyticsValue)
   