// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/pubsub/v1/data.proto

package google.events.cloud.pubsub.v1;

/**
 * <pre>
 * A message published to a topic.
 * </pre>
 *
 * Protobuf type {@code google.events.cloud.pubsub.v1.PubsubMessage}
 */
public  final class PubsubMessage extends
    com.google.protobuf.GeneratedMessageLite<
        PubsubMessage, PubsubMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:google.events.cloud.pubsub.v1.PubsubMessage)
    PubsubMessageOrBuilder {
  private PubsubMessage() {
    data_ = com.google.protobuf.ByteString.EMPTY;
    messageId_ = "";
    orderingKey_ = "";
  }
  public static final int DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString data_;
  /**
   * <pre>
   * The binary data in the message.
   * </pre>
   *
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }
  /**
   * <pre>
   * The binary data in the message.
   * </pre>
   *
   * <code>bytes data = 1;</code>
   * @param value The data to set.
   */
  private void setData(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    data_ = value;
  }
  /**
   * <pre>
   * The binary data in the message.
   * </pre>
   *
   * <code>bytes data = 1;</code>
   */
  private void clearData() {
    
    data_ = getDefaultInstance().getData();
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 2;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.String> attributes_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetAttributes() {
    return attributes_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMutableAttributes() {
    if (!attributes_.isMutable()) {
      attributes_ = attributes_.mutableCopy();
    }
    return attributes_;
  }
  @java.lang.Override

  public int getAttributesCount() {
    return internalGetAttributes().size();
  }
  /**
   * <pre>
   * Attributes for this message.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 2;</code>
   */
  @java.lang.Override

  public boolean containsAttributes(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetAttributes().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <pre>
   * Attributes for this message.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetAttributes());
  }
  /**
   * <pre>
   * Attributes for this message.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Attributes for this message.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getAttributesOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <pre>
   * Attributes for this message.
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 2;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String>
  getMutableAttributesMap() {
    return internalGetMutableAttributes();
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 3;
  private java.lang.String messageId_;
  /**
   * <pre>
   * ID of this message, assigned by the server when the message is published.
   * Guaranteed to be unique within the topic.
   * </pre>
   *
   * <code>string message_id = 3;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    return messageId_;
  }
  /**
   * <pre>
   * ID of this message, assigned by the server when the message is published.
   * Guaranteed to be unique within the topic.
   * </pre>
   *
   * <code>string message_id = 3;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageId_);
  }
  /**
   * <pre>
   * ID of this message, assigned by the server when the message is published.
   * Guaranteed to be unique within the topic.
   * </pre>
   *
   * <code>string message_id = 3;</code>
   * @param value The messageId to set.
   */
  private void setMessageId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    messageId_ = value;
  }
  /**
   * <pre>
   * ID of this message, assigned by the server when the message is published.
   * Guaranteed to be unique within the topic.
   * </pre>
   *
   * <code>string message_id = 3;</code>
   */
  private void clearMessageId() {
    
    messageId_ = getDefaultInstance().getMessageId();
  }
  /**
   * <pre>
   * ID of this message, assigned by the server when the message is published.
   * Guaranteed to be unique within the topic.
   * </pre>
   *
   * <code>string message_id = 3;</code>
   * @param value The bytes for messageId to set.
   */
  private void setMessageIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    messageId_ = value.toStringUtf8();
    
  }

  public static final int PUBLISH_TIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp publishTime_;
  /**
   * <pre>
   * The time at which the message was published, populated by the server when
   * it receives the `Publish` call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_time = 4;</code>
   */
  @java.lang.Override
  public boolean hasPublishTime() {
    return publishTime_ != null;
  }
  /**
   * <pre>
   * The time at which the message was published, populated by the server when
   * it receives the `Publish` call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_time = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPublishTime() {
    return publishTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishTime_;
  }
  /**
   * <pre>
   * The time at which the message was published, populated by the server when
   * it receives the `Publish` call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_time = 4;</code>
   */
  private void setPublishTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  publishTime_ = value;
    
    }
  /**
   * <pre>
   * The time at which the message was published, populated by the server when
   * it receives the `Publish` call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_time = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePublishTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (publishTime_ != null &&
        publishTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      publishTime_ =
        com.google.protobuf.Timestamp.newBuilder(publishTime_).mergeFrom(value).buildPartial();
    } else {
      publishTime_ = value;
    }
    
  }
  /**
   * <pre>
   * The time at which the message was published, populated by the server when
   * it receives the `Publish` call.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp publish_time = 4;</code>
   */
  private void clearPublishTime() {  publishTime_ = null;
    
  }

  public static final int ORDERING_KEY_FIELD_NUMBER = 5;
  private java.lang.String orderingKey_;
  /**
   * <pre>
   * If non-empty, identifies related messages for which publish order should be
   * respected.
   * </pre>
   *
   * <code>string ordering_key = 5;</code>
   * @return The orderingKey.
   */
  @java.lang.Override
  public java.lang.String getOrderingKey() {
    return orderingKey_;
  }
  /**
   * <pre>
   * If non-empty, identifies related messages for which publish order should be
   * respected.
   * </pre>
   *
   * <code>string ordering_key = 5;</code>
   * @return The bytes for orderingKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderingKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(orderingKey_);
  }
  /**
   * <pre>
   * If non-empty, identifies related messages for which publish order should be
   * respected.
   * </pre>
   *
   * <code>string ordering_key = 5;</code>
   * @param value The orderingKey to set.
   */
  private void setOrderingKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    orderingKey_ = value;
  }
  /**
   * <pre>
   * If non-empty, identifies related messages for which publish order should be
   * respected.
   * </pre>
   *
   * <code>string ordering_key = 5;</code>
   */
  private void clearOrderingKey() {
    
    orderingKey_ = getDefaultInstance().getOrderingKey();
  }
  /**
   * <pre>
   * If non-empty, identifies related messages for which publish order should be
   * respected.
   * </pre>
   *
   * <code>string ordering_key = 5;</code>
   * @param value The bytes for orderingKey to set.
   */
  private void setOrderingKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    orderingKey_ = value.toStringUtf8();
    
  }

  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.pubsub.v1.PubsubMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.events.cloud.pubsub.v1.PubsubMessage prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A message published to a topic.
   * </pre>
   *
   * Protobuf type {@code google.events.cloud.pubsub.v1.PubsubMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.events.cloud.pubsub.v1.PubsubMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.cloud.pubsub.v1.PubsubMessage)
      google.events.cloud.pubsub.v1.PubsubMessageOrBuilder {
    // Construct using google.events.cloud.pubsub.v1.PubsubMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The binary data in the message.
     * </pre>
     *
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <pre>
     * The binary data in the message.
     * </pre>
     *
     * <code>bytes data = 1;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <pre>
     * The binary data in the message.
     * </pre>
     *
     * <code>bytes data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    @java.lang.Override

    public int getAttributesCount() {
      return instance.getAttributesMap().size();
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */
    @java.lang.Override

    public boolean containsAttributes(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getAttributesMap().containsKey(key);
    }

    public Builder clearAttributes() {
      copyOnWrite();
      instance.getMutableAttributesMap().clear();
      return this;
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */

    public Builder removeAttributes(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableAttributesMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getAttributesMap());
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getAttributesMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getAttributesMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        java.lang.String value) {
      java.lang.Class<?> keyClass = key.getClass();
      java.lang.Class<?> valueClass = value.getClass();
      copyOnWrite();
      instance.getMutableAttributesMap().put(key, value);
      return this;
    }
    /**
     * <pre>
     * Attributes for this message.
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 2;</code>
     */
    public Builder putAllAttributes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableAttributesMap().putAll(values);
      return this;
    }

    /**
     * <pre>
     * ID of this message, assigned by the server when the message is published.
     * Guaranteed to be unique within the topic.
     * </pre>
     *
     * <code>string message_id = 3;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      return instance.getMessageId();
    }
    /**
     * <pre>
     * ID of this message, assigned by the server when the message is published.
     * Guaranteed to be unique within the topic.
     * </pre>
     *
     * <code>string message_id = 3;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      return instance.getMessageIdBytes();
    }
    /**
     * <pre>
     * ID of this message, assigned by the server when the message is published.
     * Guaranteed to be unique within the topic.
     * </pre>
     *
     * <code>string message_id = 3;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageId(value);
      return this;
    }
    /**
     * <pre>
     * ID of this message, assigned by the server when the message is published.
     * Guaranteed to be unique within the topic.
     * </pre>
     *
     * <code>string message_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      copyOnWrite();
      instance.clearMessageId();
      return this;
    }
    /**
     * <pre>
     * ID of this message, assigned by the server when the message is published.
     * Guaranteed to be unique within the topic.
     * </pre>
     *
     * <code>string message_id = 3;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The time at which the message was published, populated by the server when
     * it receives the `Publish` call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_time = 4;</code>
     */
    @java.lang.Override
    public boolean hasPublishTime() {
      return instance.hasPublishTime();
    }
    /**
     * <pre>
     * The time at which the message was published, populated by the server when
     * it receives the `Publish` call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_time = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getPublishTime() {
      return instance.getPublishTime();
    }
    /**
     * <pre>
     * The time at which the message was published, populated by the server when
     * it receives the `Publish` call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_time = 4;</code>
     */
    public Builder setPublishTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setPublishTime(value);
      return this;
      }
    /**
     * <pre>
     * The time at which the message was published, populated by the server when
     * it receives the `Publish` call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_time = 4;</code>
     */
    public Builder setPublishTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setPublishTime(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The time at which the message was published, populated by the server when
     * it receives the `Publish` call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_time = 4;</code>
     */
    public Builder mergePublishTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergePublishTime(value);
      return this;
    }
    /**
     * <pre>
     * The time at which the message was published, populated by the server when
     * it receives the `Publish` call.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp publish_time = 4;</code>
     */
    public Builder clearPublishTime() {  copyOnWrite();
      instance.clearPublishTime();
      return this;
    }

    /**
     * <pre>
     * If non-empty, identifies related messages for which publish order should be
     * respected.
     * </pre>
     *
     * <code>string ordering_key = 5;</code>
     * @return The orderingKey.
     */
    @java.lang.Override
    public java.lang.String getOrderingKey() {
      return instance.getOrderingKey();
    }
    /**
     * <pre>
     * If non-empty, identifies related messages for which publish order should be
     * respected.
     * </pre>
     *
     * <code>string ordering_key = 5;</code>
     * @return The bytes for orderingKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderingKeyBytes() {
      return instance.getOrderingKeyBytes();
    }
    /**
     * <pre>
     * If non-empty, identifies related messages for which publish order should be
     * respected.
     * </pre>
     *
     * <code>string ordering_key = 5;</code>
     * @param value The orderingKey to set.
     * @return This builder for chaining.
     */
    public Builder setOrderingKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setOrderingKey(value);
      return this;
    }
    /**
     * <pre>
     * If non-empty, identifies related messages for which publish order should be
     * respected.
     * </pre>
     *
     * <code>string ordering_key = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderingKey() {
      copyOnWrite();
      instance.clearOrderingKey();
      return this;
    }
    /**
     * <pre>
     * If non-empty, identifies related messages for which publish order should be
     * respected.
     * </pre>
     *
     * <code>string ordering_key = 5;</code>
     * @param value The bytes for orderingKey to set.
     * @return This builder for chaining.
     */
    public Builder setOrderingKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOrderingKeyBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.events.cloud.pubsub.v1.PubsubMessage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.events.cloud.pubsub.v1.PubsubMessage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "data_",
            "attributes_",
            AttributesDefaultEntryHolder.defaultEntry,
            "messageId_",
            "publishTime_",
            "orderingKey_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0001\u0000\u0000\u0001\n\u00022\u0003" +
              "\u0208\u0004\t\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.events.cloud.pubsub.v1.PubsubMessage> parser = PARSER;
        if (parser == null) {
          synchronized (google.events.cloud.pubsub.v1.PubsubMessage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.events.cloud.pubsub.v1.PubsubMessage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.events.cloud.pubsub.v1.PubsubMessage)
  private static final google.events.cloud.pubsub.v1.PubsubMessage DEFAULT_INSTANCE;
  static {
    PubsubMessage defaultInstance = new PubsubMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PubsubMessage.class, defaultInstance);
  }

  public static google.events.cloud.pubsub.v1.PubsubMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PubsubMessage> PARSER;

  public static com.google.protobuf.Parser<PubsubMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

