// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/audit/v1/data.proto

package google.events.cloud.audit.v1;

/**
 * <pre>
 * Authorization information for the operation.
 * </pre>
 *
 * Protobuf type {@code google.events.cloud.audit.v1.AuthorizationInfo}
 */
public  final class AuthorizationInfo extends
    com.google.protobuf.GeneratedMessageLite<
        AuthorizationInfo, AuthorizationInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:google.events.cloud.audit.v1.AuthorizationInfo)
    AuthorizationInfoOrBuilder {
  private AuthorizationInfo() {
    resource_ = "";
    permission_ = "";
  }
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private java.lang.String resource_;
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>string resource = 1;</code>
   * @return The resource.
   */
  @java.lang.Override
  public java.lang.String getResource() {
    return resource_;
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>string resource = 1;</code>
   * @return The bytes for resource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(resource_);
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>string resource = 1;</code>
   * @param value The resource to set.
   */
  private void setResource(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    resource_ = value;
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>string resource = 1;</code>
   */
  private void clearResource() {
    
    resource_ = getDefaultInstance().getResource();
  }
  /**
   * <pre>
   * The resource being accessed, as a REST-style string. For example:
   *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
   * </pre>
   *
   * <code>string resource = 1;</code>
   * @param value The bytes for resource to set.
   */
  private void setResourceBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    resource_ = value.toStringUtf8();
    
  }

  public static final int PERMISSION_FIELD_NUMBER = 2;
  private java.lang.String permission_;
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>string permission = 2;</code>
   * @return The permission.
   */
  @java.lang.Override
  public java.lang.String getPermission() {
    return permission_;
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>string permission = 2;</code>
   * @return The bytes for permission.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPermissionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(permission_);
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>string permission = 2;</code>
   * @param value The permission to set.
   */
  private void setPermission(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    permission_ = value;
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>string permission = 2;</code>
   */
  private void clearPermission() {
    
    permission_ = getDefaultInstance().getPermission();
  }
  /**
   * <pre>
   * The required IAM permission.
   * </pre>
   *
   * <code>string permission = 2;</code>
   * @param value The bytes for permission to set.
   */
  private void setPermissionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    permission_ = value.toStringUtf8();
    
  }

  public static final int GRANTED_FIELD_NUMBER = 3;
  private boolean granted_;
  /**
   * <pre>
   * Whether or not authorization for `resource` and `permission`
   * was granted.
   * </pre>
   *
   * <code>bool granted = 3;</code>
   * @return The granted.
   */
  @java.lang.Override
  public boolean getGranted() {
    return granted_;
  }
  /**
   * <pre>
   * Whether or not authorization for `resource` and `permission`
   * was granted.
   * </pre>
   *
   * <code>bool granted = 3;</code>
   * @param value The granted to set.
   */
  private void setGranted(boolean value) {
    
    granted_ = value;
  }
  /**
   * <pre>
   * Whether or not authorization for `resource` and `permission`
   * was granted.
   * </pre>
   *
   * <code>bool granted = 3;</code>
   */
  private void clearGranted() {
    
    granted_ = false;
  }

  public static final int RESOURCE_ATTRIBUTES_FIELD_NUMBER = 5;
  private com.google.rpc.context.AttributeContext.Resource resourceAttributes_;
  /**
   * <pre>
   * Resource attributes used in IAM condition evaluation. This field contains
   * resource attributes like resource type and resource name.
   * To get the whole view of the attributes used in IAM
   * condition evaluation, the user must also look into
   * `AuditLogData.request_metadata.request_attributes`.
   * </pre>
   *
   * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
   */
  @java.lang.Override
  public boolean hasResourceAttributes() {
    return resourceAttributes_ != null;
  }
  /**
   * <pre>
   * Resource attributes used in IAM condition evaluation. This field contains
   * resource attributes like resource type and resource name.
   * To get the whole view of the attributes used in IAM
   * condition evaluation, the user must also look into
   * `AuditLogData.request_metadata.request_attributes`.
   * </pre>
   *
   * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
   */
  @java.lang.Override
  public com.google.rpc.context.AttributeContext.Resource getResourceAttributes() {
    return resourceAttributes_ == null ? com.google.rpc.context.AttributeContext.Resource.getDefaultInstance() : resourceAttributes_;
  }
  /**
   * <pre>
   * Resource attributes used in IAM condition evaluation. This field contains
   * resource attributes like resource type and resource name.
   * To get the whole view of the attributes used in IAM
   * condition evaluation, the user must also look into
   * `AuditLogData.request_metadata.request_attributes`.
   * </pre>
   *
   * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
   */
  private void setResourceAttributes(com.google.rpc.context.AttributeContext.Resource value) {
    value.getClass();
  resourceAttributes_ = value;
    
    }
  /**
   * <pre>
   * Resource attributes used in IAM condition evaluation. This field contains
   * resource attributes like resource type and resource name.
   * To get the whole view of the attributes used in IAM
   * condition evaluation, the user must also look into
   * `AuditLogData.request_metadata.request_attributes`.
   * </pre>
   *
   * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeResourceAttributes(com.google.rpc.context.AttributeContext.Resource value) {
    value.getClass();
  if (resourceAttributes_ != null &&
        resourceAttributes_ != com.google.rpc.context.AttributeContext.Resource.getDefaultInstance()) {
      resourceAttributes_ =
        com.google.rpc.context.AttributeContext.Resource.newBuilder(resourceAttributes_).mergeFrom(value).buildPartial();
    } else {
      resourceAttributes_ = value;
    }
    
  }
  /**
   * <pre>
   * Resource attributes used in IAM condition evaluation. This field contains
   * resource attributes like resource type and resource name.
   * To get the whole view of the attributes used in IAM
   * condition evaluation, the user must also look into
   * `AuditLogData.request_metadata.request_attributes`.
   * </pre>
   *
   * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
   */
  private void clearResourceAttributes() {  resourceAttributes_ = null;
    
  }

  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.audit.v1.AuthorizationInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.events.cloud.audit.v1.AuthorizationInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Authorization information for the operation.
   * </pre>
   *
   * Protobuf type {@code google.events.cloud.audit.v1.AuthorizationInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.events.cloud.audit.v1.AuthorizationInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.cloud.audit.v1.AuthorizationInfo)
      google.events.cloud.audit.v1.AuthorizationInfoOrBuilder {
    // Construct using google.events.cloud.audit.v1.AuthorizationInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>string resource = 1;</code>
     * @return The resource.
     */
    @java.lang.Override
    public java.lang.String getResource() {
      return instance.getResource();
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>string resource = 1;</code>
     * @return The bytes for resource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResourceBytes() {
      return instance.getResourceBytes();
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>string resource = 1;</code>
     * @param value The resource to set.
     * @return This builder for chaining.
     */
    public Builder setResource(
        java.lang.String value) {
      copyOnWrite();
      instance.setResource(value);
      return this;
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>string resource = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResource() {
      copyOnWrite();
      instance.clearResource();
      return this;
    }
    /**
     * <pre>
     * The resource being accessed, as a REST-style string. For example:
     *     bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
     * </pre>
     *
     * <code>string resource = 1;</code>
     * @param value The bytes for resource to set.
     * @return This builder for chaining.
     */
    public Builder setResourceBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResourceBytes(value);
      return this;
    }

    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>string permission = 2;</code>
     * @return The permission.
     */
    @java.lang.Override
    public java.lang.String getPermission() {
      return instance.getPermission();
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>string permission = 2;</code>
     * @return The bytes for permission.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPermissionBytes() {
      return instance.getPermissionBytes();
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>string permission = 2;</code>
     * @param value The permission to set.
     * @return This builder for chaining.
     */
    public Builder setPermission(
        java.lang.String value) {
      copyOnWrite();
      instance.setPermission(value);
      return this;
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>string permission = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPermission() {
      copyOnWrite();
      instance.clearPermission();
      return this;
    }
    /**
     * <pre>
     * The required IAM permission.
     * </pre>
     *
     * <code>string permission = 2;</code>
     * @param value The bytes for permission to set.
     * @return This builder for chaining.
     */
    public Builder setPermissionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPermissionBytes(value);
      return this;
    }

    /**
     * <pre>
     * Whether or not authorization for `resource` and `permission`
     * was granted.
     * </pre>
     *
     * <code>bool granted = 3;</code>
     * @return The granted.
     */
    @java.lang.Override
    public boolean getGranted() {
      return instance.getGranted();
    }
    /**
     * <pre>
     * Whether or not authorization for `resource` and `permission`
     * was granted.
     * </pre>
     *
     * <code>bool granted = 3;</code>
     * @param value The granted to set.
     * @return This builder for chaining.
     */
    public Builder setGranted(boolean value) {
      copyOnWrite();
      instance.setGranted(value);
      return this;
    }
    /**
     * <pre>
     * Whether or not authorization for `resource` and `permission`
     * was granted.
     * </pre>
     *
     * <code>bool granted = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGranted() {
      copyOnWrite();
      instance.clearGranted();
      return this;
    }

    /**
     * <pre>
     * Resource attributes used in IAM condition evaluation. This field contains
     * resource attributes like resource type and resource name.
     * To get the whole view of the attributes used in IAM
     * condition evaluation, the user must also look into
     * `AuditLogData.request_metadata.request_attributes`.
     * </pre>
     *
     * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
     */
    @java.lang.Override
    public boolean hasResourceAttributes() {
      return instance.hasResourceAttributes();
    }
    /**
     * <pre>
     * Resource attributes used in IAM condition evaluation. This field contains
     * resource attributes like resource type and resource name.
     * To get the whole view of the attributes used in IAM
     * condition evaluation, the user must also look into
     * `AuditLogData.request_metadata.request_attributes`.
     * </pre>
     *
     * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
     */
    @java.lang.Override
    public com.google.rpc.context.AttributeContext.Resource getResourceAttributes() {
      return instance.getResourceAttributes();
    }
    /**
     * <pre>
     * Resource attributes used in IAM condition evaluation. This field contains
     * resource attributes like resource type and resource name.
     * To get the whole view of the attributes used in IAM
     * condition evaluation, the user must also look into
     * `AuditLogData.request_metadata.request_attributes`.
     * </pre>
     *
     * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
     */
    public Builder setResourceAttributes(com.google.rpc.context.AttributeContext.Resource value) {
      copyOnWrite();
      instance.setResourceAttributes(value);
      return this;
      }
    /**
     * <pre>
     * Resource attributes used in IAM condition evaluation. This field contains
     * resource attributes like resource type and resource name.
     * To get the whole view of the attributes used in IAM
     * condition evaluation, the user must also look into
     * `AuditLogData.request_metadata.request_attributes`.
     * </pre>
     *
     * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
     */
    public Builder setResourceAttributes(
        com.google.rpc.context.AttributeContext.Resource.Builder builderForValue) {
      copyOnWrite();
      instance.setResourceAttributes(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Resource attributes used in IAM condition evaluation. This field contains
     * resource attributes like resource type and resource name.
     * To get the whole view of the attributes used in IAM
     * condition evaluation, the user must also look into
     * `AuditLogData.request_metadata.request_attributes`.
     * </pre>
     *
     * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
     */
    public Builder mergeResourceAttributes(com.google.rpc.context.AttributeContext.Resource value) {
      copyOnWrite();
      instance.mergeResourceAttributes(value);
      return this;
    }
    /**
     * <pre>
     * Resource attributes used in IAM condition evaluation. This field contains
     * resource attributes like resource type and resource name.
     * To get the whole view of the attributes used in IAM
     * condition evaluation, the user must also look into
     * `AuditLogData.request_metadata.request_attributes`.
     * </pre>
     *
     * <code>.google.rpc.context.AttributeContext.Resource resource_attributes = 5;</code>
     */
    public Builder clearResourceAttributes() {  copyOnWrite();
      instance.clearResourceAttributes();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.events.cloud.audit.v1.AuthorizationInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.events.cloud.audit.v1.AuthorizationInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "resource_",
            "permission_",
            "granted_",
            "resourceAttributes_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0005\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0007\u0005\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.events.cloud.audit.v1.AuthorizationInfo> parser = PARSER;
        if (parser == null) {
          synchronized (google.events.cloud.audit.v1.AuthorizationInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.events.cloud.audit.v1.AuthorizationInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.events.cloud.audit.v1.AuthorizationInfo)
  private static final google.events.cloud.audit.v1.AuthorizationInfo DEFAULT_INSTANCE;
  static {
    AuthorizationInfo defaultInstance = new AuthorizationInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AuthorizationInfo.class, defaultInstance);
  }

  public static google.events.cloud.audit.v1.AuthorizationInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthorizationInfo> PARSER;

  public static com.google.protobuf.Parser<AuthorizationInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

