// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/audit/v1/data.proto

package google.events.cloud.audit.v1;

/**
 * <pre>
 * Location information about a resource.
 * </pre>
 *
 * Protobuf type {@code google.events.cloud.audit.v1.ResourceLocation}
 */
public  final class ResourceLocation extends
    com.google.protobuf.GeneratedMessageLite<
        ResourceLocation, ResourceLocation.Builder> implements
    // @@protoc_insertion_point(message_implements:google.events.cloud.audit.v1.ResourceLocation)
    ResourceLocationOrBuilder {
  private ResourceLocation() {
    currentLocations_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    originalLocations_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int CURRENT_LOCATIONS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> currentLocations_;
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @return A list containing the currentLocations.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getCurrentLocationsList() {
    return currentLocations_;
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @return The count of currentLocations.
   */
  @java.lang.Override
  public int getCurrentLocationsCount() {
    return currentLocations_.size();
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @param index The index of the element to return.
   * @return The currentLocations at the given index.
   */
  @java.lang.Override
  public java.lang.String getCurrentLocations(int index) {
    return currentLocations_.get(index);
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the currentLocations at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentLocationsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        currentLocations_.get(index));
  }
  private void ensureCurrentLocationsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        currentLocations_;  if (!tmp.isModifiable()) {
      currentLocations_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @param index The index to set the value at.
   * @param value The currentLocations to set.
   */
  private void setCurrentLocations(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCurrentLocationsIsMutable();
    currentLocations_.set(index, value);
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @param value The currentLocations to add.
   */
  private void addCurrentLocations(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCurrentLocationsIsMutable();
    currentLocations_.add(value);
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @param values The currentLocations to add.
   */
  private void addAllCurrentLocations(
      java.lang.Iterable<java.lang.String> values) {
    ensureCurrentLocationsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, currentLocations_);
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   */
  private void clearCurrentLocations() {
    currentLocations_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * The locations of a resource after the execution of the operation.
   * Requests to create or delete a location based resource must populate
   * the 'current_locations' field and not the 'original_locations' field.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string current_locations = 1;</code>
   * @param value The bytes of the currentLocations to add.
   */
  private void addCurrentLocationsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureCurrentLocationsIsMutable();
    currentLocations_.add(value.toStringUtf8());
  }

  public static final int ORIGINAL_LOCATIONS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> originalLocations_;
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @return A list containing the originalLocations.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getOriginalLocationsList() {
    return originalLocations_;
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @return The count of originalLocations.
   */
  @java.lang.Override
  public int getOriginalLocationsCount() {
    return originalLocations_.size();
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @param index The index of the element to return.
   * @return The originalLocations at the given index.
   */
  @java.lang.Override
  public java.lang.String getOriginalLocations(int index) {
    return originalLocations_.get(index);
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the originalLocations at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalLocationsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        originalLocations_.get(index));
  }
  private void ensureOriginalLocationsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        originalLocations_;  if (!tmp.isModifiable()) {
      originalLocations_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @param index The index to set the value at.
   * @param value The originalLocations to set.
   */
  private void setOriginalLocations(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureOriginalLocationsIsMutable();
    originalLocations_.set(index, value);
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @param value The originalLocations to add.
   */
  private void addOriginalLocations(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureOriginalLocationsIsMutable();
    originalLocations_.add(value);
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @param values The originalLocations to add.
   */
  private void addAllOriginalLocations(
      java.lang.Iterable<java.lang.String> values) {
    ensureOriginalLocationsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, originalLocations_);
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   */
  private void clearOriginalLocations() {
    originalLocations_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * The locations of a resource prior to the execution of the operation.
   * Requests that mutate the resource's location must populate both the
   * 'original_locations' as well as the 'current_locations' fields.
   * For example:
   *     "europe-west1-a"
   *     "us-east1"
   *     "nam3"
   * </pre>
   *
   * <code>repeated string original_locations = 2;</code>
   * @param value The bytes of the originalLocations to add.
   */
  private void addOriginalLocationsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureOriginalLocationsIsMutable();
    originalLocations_.add(value.toStringUtf8());
  }

  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.audit.v1.ResourceLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.events.cloud.audit.v1.ResourceLocation prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Location information about a resource.
   * </pre>
   *
   * Protobuf type {@code google.events.cloud.audit.v1.ResourceLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.events.cloud.audit.v1.ResourceLocation, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.cloud.audit.v1.ResourceLocation)
      google.events.cloud.audit.v1.ResourceLocationOrBuilder {
    // Construct using google.events.cloud.audit.v1.ResourceLocation.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @return A list containing the currentLocations.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getCurrentLocationsList() {
      return java.util.Collections.unmodifiableList(
          instance.getCurrentLocationsList());
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @return The count of currentLocations.
     */
    @java.lang.Override
    public int getCurrentLocationsCount() {
      return instance.getCurrentLocationsCount();
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @param index The index of the element to return.
     * @return The currentLocations at the given index.
     */
    @java.lang.Override
    public java.lang.String getCurrentLocations(int index) {
      return instance.getCurrentLocations(index);
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the currentLocations at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentLocationsBytes(int index) {
      return instance.getCurrentLocationsBytes(index);
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @param index The index to set the value at.
     * @param value The currentLocations to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentLocations(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setCurrentLocations(index, value);
      return this;
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @param value The currentLocations to add.
     * @return This builder for chaining.
     */
    public Builder addCurrentLocations(
        java.lang.String value) {
      copyOnWrite();
      instance.addCurrentLocations(value);
      return this;
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @param values The currentLocations to add.
     * @return This builder for chaining.
     */
    public Builder addAllCurrentLocations(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllCurrentLocations(values);
      return this;
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentLocations() {
      copyOnWrite();
      instance.clearCurrentLocations();
      return this;
    }
    /**
     * <pre>
     * The locations of a resource after the execution of the operation.
     * Requests to create or delete a location based resource must populate
     * the 'current_locations' field and not the 'original_locations' field.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string current_locations = 1;</code>
     * @param value The bytes of the currentLocations to add.
     * @return This builder for chaining.
     */
    public Builder addCurrentLocationsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addCurrentLocationsBytes(value);
      return this;
    }

    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @return A list containing the originalLocations.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getOriginalLocationsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOriginalLocationsList());
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @return The count of originalLocations.
     */
    @java.lang.Override
    public int getOriginalLocationsCount() {
      return instance.getOriginalLocationsCount();
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @param index The index of the element to return.
     * @return The originalLocations at the given index.
     */
    @java.lang.Override
    public java.lang.String getOriginalLocations(int index) {
      return instance.getOriginalLocations(index);
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the originalLocations at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOriginalLocationsBytes(int index) {
      return instance.getOriginalLocationsBytes(index);
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @param index The index to set the value at.
     * @param value The originalLocations to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalLocations(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setOriginalLocations(index, value);
      return this;
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @param value The originalLocations to add.
     * @return This builder for chaining.
     */
    public Builder addOriginalLocations(
        java.lang.String value) {
      copyOnWrite();
      instance.addOriginalLocations(value);
      return this;
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @param values The originalLocations to add.
     * @return This builder for chaining.
     */
    public Builder addAllOriginalLocations(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllOriginalLocations(values);
      return this;
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalLocations() {
      copyOnWrite();
      instance.clearOriginalLocations();
      return this;
    }
    /**
     * <pre>
     * The locations of a resource prior to the execution of the operation.
     * Requests that mutate the resource's location must populate both the
     * 'original_locations' as well as the 'current_locations' fields.
     * For example:
     *     "europe-west1-a"
     *     "us-east1"
     *     "nam3"
     * </pre>
     *
     * <code>repeated string original_locations = 2;</code>
     * @param value The bytes of the originalLocations to add.
     * @return This builder for chaining.
     */
    public Builder addOriginalLocationsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addOriginalLocationsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.events.cloud.audit.v1.ResourceLocation)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.events.cloud.audit.v1.ResourceLocation();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "currentLocations_",
            "originalLocations_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0002\u0000\u0001\u021a\u0002\u021a" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.events.cloud.audit.v1.ResourceLocation> parser = PARSER;
        if (parser == null) {
          synchronized (google.events.cloud.audit.v1.ResourceLocation.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.events.cloud.audit.v1.ResourceLocation>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.events.cloud.audit.v1.ResourceLocation)
  private static final google.events.cloud.audit.v1.ResourceLocation DEFAULT_INSTANCE;
  static {
    ResourceLocation defaultInstance = new ResourceLocation();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ResourceLocation.class, defaultInstance);
  }

  public static google.events.cloud.audit.v1.ResourceLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ResourceLocation> PARSER;

  public static com.google.protobuf.Parser<ResourceLocation> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

