// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/remoteconfig/v1/data.proto

package google.events.firebase.remoteconfig.v1;

/**
 * <pre>
 * What type of update was associated with the Remote Config template version.
 * </pre>
 *
 * Protobuf enum {@code google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin}
 */
public enum RemoteConfigUpdateOrigin
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * Catch-all for unrecognized values.
   * </pre>
   *
   * <code>REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED = 0;</code>
   */
  REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED(0),
  /**
   * <pre>
   * The update came from the Firebase UI.
   * </pre>
   *
   * <code>CONSOLE = 1;</code>
   */
  CONSOLE(1),
  /**
   * <pre>
   * The update came from the Remote Config REST API.
   * </pre>
   *
   * <code>REST_API = 2;</code>
   */
  REST_API(2),
  /**
   * <pre>
   * The update came from the Firebase Admin Node SDK.
   * </pre>
   *
   * <code>ADMIN_SDK_NODE = 3;</code>
   */
  ADMIN_SDK_NODE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Catch-all for unrecognized values.
   * </pre>
   *
   * <code>REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED = 0;</code>
   */
  public static final int REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * The update came from the Firebase UI.
   * </pre>
   *
   * <code>CONSOLE = 1;</code>
   */
  public static final int CONSOLE_VALUE = 1;
  /**
   * <pre>
   * The update came from the Remote Config REST API.
   * </pre>
   *
   * <code>REST_API = 2;</code>
   */
  public static final int REST_API_VALUE = 2;
  /**
   * <pre>
   * The update came from the Firebase Admin Node SDK.
   * </pre>
   *
   * <code>ADMIN_SDK_NODE = 3;</code>
   */
  public static final int ADMIN_SDK_NODE_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RemoteConfigUpdateOrigin valueOf(int value) {
    return forNumber(value);
  }

  public static RemoteConfigUpdateOrigin forNumber(int value) {
    switch (value) {
      case 0: return REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED;
      case 1: return CONSOLE;
      case 2: return REST_API;
      case 3: return ADMIN_SDK_NODE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RemoteConfigUpdateOrigin>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RemoteConfigUpdateOrigin> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RemoteConfigUpdateOrigin>() {
          @java.lang.Override
          public RemoteConfigUpdateOrigin findValueByNumber(int number) {
            return RemoteConfigUpdateOrigin.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return RemoteConfigUpdateOriginVerifier.INSTANCE;
  }

  private static final class RemoteConfigUpdateOriginVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new RemoteConfigUpdateOriginVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return RemoteConfigUpdateOrigin.forNumber(number) != null;
          }
        };

  private final int value;

  private RemoteConfigUpdateOrigin(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin)
}

