// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/iot/v1/data.proto

package google.events.cloud.iot.v1;

/**
 * <pre>
 * Indicates whether DeviceService (HTTP) is enabled or disabled for the
 * registry. See the field description for details.
 * </pre>
 *
 * Protobuf enum {@code google.events.cloud.iot.v1.HttpState}
 */
public enum HttpState
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * No HTTP state specified. If not specified, DeviceService will be
   * enabled by default.
   * </pre>
   *
   * <code>HTTP_STATE_UNSPECIFIED = 0;</code>
   */
  HTTP_STATE_UNSPECIFIED(0),
  /**
   * <pre>
   * Enables DeviceService (HTTP) service for the registry.
   * </pre>
   *
   * <code>HTTP_ENABLED = 1;</code>
   */
  HTTP_ENABLED(1),
  /**
   * <pre>
   * Disables DeviceService (HTTP) service for the registry.
   * </pre>
   *
   * <code>HTTP_DISABLED = 2;</code>
   */
  HTTP_DISABLED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * No HTTP state specified. If not specified, DeviceService will be
   * enabled by default.
   * </pre>
   *
   * <code>HTTP_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int HTTP_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Enables DeviceService (HTTP) service for the registry.
   * </pre>
   *
   * <code>HTTP_ENABLED = 1;</code>
   */
  public static final int HTTP_ENABLED_VALUE = 1;
  /**
   * <pre>
   * Disables DeviceService (HTTP) service for the registry.
   * </pre>
   *
   * <code>HTTP_DISABLED = 2;</code>
   */
  public static final int HTTP_DISABLED_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HttpState valueOf(int value) {
    return forNumber(value);
  }

  public static HttpState forNumber(int value) {
    switch (value) {
      case 0: return HTTP_STATE_UNSPECIFIED;
      case 1: return HTTP_ENABLED;
      case 2: return HTTP_DISABLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HttpState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HttpState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HttpState>() {
          @java.lang.Override
          public HttpState findValueByNumber(int number) {
            return HttpState.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return HttpStateVerifier.INSTANCE;
  }

  private static final class HttpStateVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new HttpStateVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return HttpState.forNumber(number) != null;
          }
        };

  private final int value;

  private HttpState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.events.cloud.iot.v1.HttpState)
}

