// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/firebasealerts/v1/cloud_event_payload.proto

package google.events.firebase.firebasealerts.v1;

public interface CrashlyticsStabilityDigestPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The date that the digest gets created, issues in the digest should
   * have the same date as the digest date
   * </pre>
   *
   * <code>.google.type.Date digest_date = 5;</code>
   * @return Whether the digestDate field is set.
   */
  boolean hasDigestDate();
  /**
   * <pre>
   * The date that the digest gets created, issues in the digest should
   * have the same date as the digest date
   * </pre>
   *
   * <code>.google.type.Date digest_date = 5;</code>
   * @return The digestDate.
   */
  com.google.type.Date getDigestDate();

  /**
   * <pre>
   * A stability digest contains several trending Crashlytics issues
   * </pre>
   *
   * <code>repeated .google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails trending_issues = 6;</code>
   */
  java.util.List<google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails> 
      getTrendingIssuesList();
  /**
   * <pre>
   * A stability digest contains several trending Crashlytics issues
   * </pre>
   *
   * <code>repeated .google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails trending_issues = 6;</code>
   */
  google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails getTrendingIssues(int index);
  /**
   * <pre>
   * A stability digest contains several trending Crashlytics issues
   * </pre>
   *
   * <code>repeated .google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails trending_issues = 6;</code>
   */
  int getTrendingIssuesCount();
}
