|- Device(id: STRING, name: STRING, num_id: UINT64, credentials: List<DeviceCredential>, last_heartbeat_time: Timestamp, last_event_time: Timestamp, last_state_time: Timestamp, last_config_ack_time: Timestamp, last_config_send_time: Timestamp, blocked: BOOL, last_error_time: Timestamp, last_error_status: Status, config: DeviceConfig, state: DeviceState, log_level: ENUM, metadata: List<MetadataEntry>, gateway_config: GatewayConfig)
   |- MetadataEntry(key: STRING, value: STRING)
   |- GatewayConfig(gateway_type: ENUM, gateway_auth_method: ENUM, last_accessed_gateway_id: STRING, last_accessed_gateway_time: Timestamp)
|- DeviceRegistry(id: STRING, name: STRING, event_notification_configs: List<EventNotificationConfig>, state_notification_config: StateNotificationConfig, mqtt_config: MqttConfig, http_config: HttpConfig, log_level: ENUM, credentials: List<RegistryCredential>)
|- MqttConfig(mqtt_enabled_state: ENUM)
|- HttpConfig(http_enabled_state: ENUM)
|- EventNotificationConfig(subfolder_matches: STRING, pubsub_topic_name: STRING)
|- StateNotificationConfig(pubsub_topic_name: STRING)
|- RegistryCredential(public_key_certificate: PublicKeyCertificate)
|- X509CertificateDetails(issuer: STRING, subject: STRING, start_time: Timestamp, expiry_time: Timestamp, signature_algorithm: STRING, public_key_type: STRING)
|- PublicKeyCertificate(format: ENUM, certificate: STRING, x509_details: X509CertificateDetails)
|- DeviceCredential(public_key: PublicKeyCredential, expiration_time: Timestamp)
|- PublicKeyCredential(format: ENUM, key: STRING)
|- DeviceConfig(version: INT64, cloud_update_time: Timestamp, device_ack_time: Timestamp, binary_data: BYTES)
|- DeviceState(update_time: Timestamp, binary_data: BYTES)
|- DeviceEventData(payload: Device)
|- RegistryEventData(payload: DeviceRegistry)
