// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/cloudbuild/v1/data.proto

package google.events.cloud.cloudbuild.v1;

/**
 * <pre>
 * Pairs a set of secret environment variables containing encrypted
 * values with the Cloud KMS key to use to decrypt the value.
 * </pre>
 *
 * Protobuf type {@code google.events.cloud.cloudbuild.v1.Secret}
 */
public  final class Secret extends
    com.google.protobuf.GeneratedMessageLite<
        Secret, Secret.Builder> implements
    // @@protoc_insertion_point(message_implements:google.events.cloud.cloudbuild.v1.Secret)
    SecretOrBuilder {
  private Secret() {
    kmsKeyName_ = "";
  }
  public static final int KMS_KEY_NAME_FIELD_NUMBER = 1;
  private java.lang.String kmsKeyName_;
  /**
   * <pre>
   * Cloud KMS key name to use to decrypt these envs.
   * </pre>
   *
   * <code>string kms_key_name = 1;</code>
   * @return The kmsKeyName.
   */
  @java.lang.Override
  public java.lang.String getKmsKeyName() {
    return kmsKeyName_;
  }
  /**
   * <pre>
   * Cloud KMS key name to use to decrypt these envs.
   * </pre>
   *
   * <code>string kms_key_name = 1;</code>
   * @return The bytes for kmsKeyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKmsKeyNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(kmsKeyName_);
  }
  /**
   * <pre>
   * Cloud KMS key name to use to decrypt these envs.
   * </pre>
   *
   * <code>string kms_key_name = 1;</code>
   * @param value The kmsKeyName to set.
   */
  private void setKmsKeyName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    kmsKeyName_ = value;
  }
  /**
   * <pre>
   * Cloud KMS key name to use to decrypt these envs.
   * </pre>
   *
   * <code>string kms_key_name = 1;</code>
   */
  private void clearKmsKeyName() {
    
    kmsKeyName_ = getDefaultInstance().getKmsKeyName();
  }
  /**
   * <pre>
   * Cloud KMS key name to use to decrypt these envs.
   * </pre>
   *
   * <code>string kms_key_name = 1;</code>
   * @param value The bytes for kmsKeyName to set.
   */
  private void setKmsKeyNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    kmsKeyName_ = value.toStringUtf8();
    
  }

  public static final int SECRET_ENV_FIELD_NUMBER = 3;
  private static final class SecretEnvDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, com.google.protobuf.ByteString> secretEnv_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, com.google.protobuf.ByteString>
  internalGetSecretEnv() {
    return secretEnv_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, com.google.protobuf.ByteString>
  internalGetMutableSecretEnv() {
    if (!secretEnv_.isMutable()) {
      secretEnv_ = secretEnv_.mutableCopy();
    }
    return secretEnv_;
  }
  @java.lang.Override

  public int getSecretEnvCount() {
    return internalGetSecretEnv().size();
  }
  /**
   * <pre>
   * Map of environment variable name to its encrypted value.
   * Secret environment variables must be unique across all of a build's
   * secrets, and must be used by at least one build step. Values can be at most
   * 64 KB in size. There can be at most 100 secret values across all of a
   * build's secrets.
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
   */
  @java.lang.Override

  public boolean containsSecretEnv(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetSecretEnv().containsKey(key);
  }
  /**
   * Use {@link #getSecretEnvMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getSecretEnv() {
    return getSecretEnvMap();
  }
  /**
   * <pre>
   * Map of environment variable name to its encrypted value.
   * Secret environment variables must be unique across all of a build's
   * secrets, and must be used by at least one build step. Values can be at most
   * 64 KB in size. There can be at most 100 secret values across all of a
   * build's secrets.
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getSecretEnvMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetSecretEnv());
  }
  /**
   * <pre>
   * Map of environment variable name to its encrypted value.
   * Secret environment variables must be unique across all of a build's
   * secrets, and must be used by at least one build step. Values can be at most
   * 64 KB in size. There can be at most 100 secret values across all of a
   * build's secrets.
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
   */
  @java.lang.Override

  public com.google.protobuf.ByteString getSecretEnvOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetSecretEnv();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Map of environment variable name to its encrypted value.
   * Secret environment variables must be unique across all of a build's
   * secrets, and must be used by at least one build step. Values can be at most
   * 64 KB in size. There can be at most 100 secret values across all of a
   * build's secrets.
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
   */
  @java.lang.Override

  public com.google.protobuf.ByteString getSecretEnvOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetSecretEnv();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <pre>
   * Map of environment variable name to its encrypted value.
   * Secret environment variables must be unique across all of a build's
   * secrets, and must be used by at least one build step. Values can be at most
   * 64 KB in size. There can be at most 100 secret values across all of a
   * build's secrets.
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
   */
  private java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getMutableSecretEnvMap() {
    return internalGetMutableSecretEnv();
  }

  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.cloudbuild.v1.Secret parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.events.cloud.cloudbuild.v1.Secret prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Pairs a set of secret environment variables containing encrypted
   * values with the Cloud KMS key to use to decrypt the value.
   * </pre>
   *
   * Protobuf type {@code google.events.cloud.cloudbuild.v1.Secret}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.events.cloud.cloudbuild.v1.Secret, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.cloud.cloudbuild.v1.Secret)
      google.events.cloud.cloudbuild.v1.SecretOrBuilder {
    // Construct using google.events.cloud.cloudbuild.v1.Secret.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Cloud KMS key name to use to decrypt these envs.
     * </pre>
     *
     * <code>string kms_key_name = 1;</code>
     * @return The kmsKeyName.
     */
    @java.lang.Override
    public java.lang.String getKmsKeyName() {
      return instance.getKmsKeyName();
    }
    /**
     * <pre>
     * Cloud KMS key name to use to decrypt these envs.
     * </pre>
     *
     * <code>string kms_key_name = 1;</code>
     * @return The bytes for kmsKeyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKmsKeyNameBytes() {
      return instance.getKmsKeyNameBytes();
    }
    /**
     * <pre>
     * Cloud KMS key name to use to decrypt these envs.
     * </pre>
     *
     * <code>string kms_key_name = 1;</code>
     * @param value The kmsKeyName to set.
     * @return This builder for chaining.
     */
    public Builder setKmsKeyName(
        java.lang.String value) {
      copyOnWrite();
      instance.setKmsKeyName(value);
      return this;
    }
    /**
     * <pre>
     * Cloud KMS key name to use to decrypt these envs.
     * </pre>
     *
     * <code>string kms_key_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKmsKeyName() {
      copyOnWrite();
      instance.clearKmsKeyName();
      return this;
    }
    /**
     * <pre>
     * Cloud KMS key name to use to decrypt these envs.
     * </pre>
     *
     * <code>string kms_key_name = 1;</code>
     * @param value The bytes for kmsKeyName to set.
     * @return This builder for chaining.
     */
    public Builder setKmsKeyNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKmsKeyNameBytes(value);
      return this;
    }

    @java.lang.Override

    public int getSecretEnvCount() {
      return instance.getSecretEnvMap().size();
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */
    @java.lang.Override

    public boolean containsSecretEnv(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getSecretEnvMap().containsKey(key);
    }

    public Builder clearSecretEnv() {
      copyOnWrite();
      instance.getMutableSecretEnvMap().clear();
      return this;
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */

    public Builder removeSecretEnv(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableSecretEnvMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getSecretEnvMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getSecretEnv() {
      return getSecretEnvMap();
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getSecretEnvMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getSecretEnvMap());
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getSecretEnvOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          instance.getSecretEnvMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getSecretEnvOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          instance.getSecretEnvMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */
    public Builder putSecretEnv(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      java.lang.Class<?> keyClass = key.getClass();
      java.lang.Class<?> valueClass = value.getClass();
      copyOnWrite();
      instance.getMutableSecretEnvMap().put(key, value);
      return this;
    }
    /**
     * <pre>
     * Map of environment variable name to its encrypted value.
     * Secret environment variables must be unique across all of a build's
     * secrets, and must be used by at least one build step. Values can be at most
     * 64 KB in size. There can be at most 100 secret values across all of a
     * build's secrets.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; secret_env = 3;</code>
     */
    public Builder putAllSecretEnv(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      copyOnWrite();
      instance.getMutableSecretEnvMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.events.cloud.cloudbuild.v1.Secret)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.events.cloud.cloudbuild.v1.Secret();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "kmsKeyName_",
            "secretEnv_",
            SecretEnvDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0003\u0002\u0001\u0000\u0000\u0001\u0208\u00032";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.events.cloud.cloudbuild.v1.Secret> parser = PARSER;
        if (parser == null) {
          synchronized (google.events.cloud.cloudbuild.v1.Secret.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.events.cloud.cloudbuild.v1.Secret>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.events.cloud.cloudbuild.v1.Secret)
  private static final google.events.cloud.cloudbuild.v1.Secret DEFAULT_INSTANCE;
  static {
    Secret defaultInstance = new Secret();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Secret.class, defaultInstance);
  }

  public static google.events.cloud.cloudbuild.v1.Secret getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Secret> PARSER;

  public static com.google.protobuf.Parser<Secret> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

