// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/firestore/v1/data.proto

package google.events.cloud.firestore.v1;

/**
 * <pre>
 * A message that can hold any of the supported value types.
 * </pre>
 *
 * Protobuf type {@code google.events.cloud.firestore.v1.Value}
 */
public  final class Value extends
    com.google.protobuf.GeneratedMessageLite<
        Value, Value.Builder> implements
    // @@protoc_insertion_point(message_implements:google.events.cloud.firestore.v1.Value)
    ValueOrBuilder {
  private Value() {
  }
  private int valueTypeCase_ = 0;
  private java.lang.Object valueType_;
  public enum ValueTypeCase {
    NULL_VALUE(11),
    BOOLEAN_VALUE(1),
    INTEGER_VALUE(2),
    DOUBLE_VALUE(3),
    TIMESTAMP_VALUE(10),
    STRING_VALUE(17),
    BYTES_VALUE(18),
    REFERENCE_VALUE(5),
    GEO_POINT_VALUE(8),
    ARRAY_VALUE(9),
    MAP_VALUE(6),
    VALUETYPE_NOT_SET(0);
    private final int value;
    private ValueTypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueTypeCase forNumber(int value) {
      switch (value) {
        case 11: return NULL_VALUE;
        case 1: return BOOLEAN_VALUE;
        case 2: return INTEGER_VALUE;
        case 3: return DOUBLE_VALUE;
        case 10: return TIMESTAMP_VALUE;
        case 17: return STRING_VALUE;
        case 18: return BYTES_VALUE;
        case 5: return REFERENCE_VALUE;
        case 8: return GEO_POINT_VALUE;
        case 9: return ARRAY_VALUE;
        case 6: return MAP_VALUE;
        case 0: return VALUETYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ValueTypeCase
  getValueTypeCase() {
    return ValueTypeCase.forNumber(
        valueTypeCase_);
  }

  private void clearValueType() {
    valueTypeCase_ = 0;
    valueType_ = null;
  }

  public static final int NULL_VALUE_FIELD_NUMBER = 11;
  /**
   * <pre>
   * A null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 11;</code>
   * @return Whether the nullValue field is set.
   */
  @java.lang.Override
  public boolean hasNullValue() {
    return valueTypeCase_ == 11;
  }
  /**
   * <pre>
   * A null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 11;</code>
   * @return The enum numeric value on the wire for nullValue.
   */
  @java.lang.Override
  public int getNullValueValue() {
    if (valueTypeCase_ == 11) {
      return (java.lang.Integer) valueType_;
    }
    return 0;
  }
  /**
   * <pre>
   * A null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 11;</code>
   * @return The nullValue.
   */
  @java.lang.Override
  public com.google.protobuf.NullValue getNullValue() {
    if (valueTypeCase_ == 11) {
      com.google.protobuf.NullValue result = com.google.protobuf.NullValue.forNumber((java.lang.Integer) valueType_);
      return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
    }
    return com.google.protobuf.NullValue.NULL_VALUE;
  }
  /**
   * <pre>
   * A null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 11;</code>
   * @param value The enum numeric value on the wire for nullValue to set.
   */
  private void setNullValueValue(int value) {
    valueTypeCase_ = 11;
    valueType_ = value;
  }
  /**
   * <pre>
   * A null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 11;</code>
   * @param value The nullValue to set.
   */
  private void setNullValue(com.google.protobuf.NullValue value) {
    valueType_ = value.getNumber();
    valueTypeCase_ = 11;
  }
  /**
   * <pre>
   * A null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 11;</code>
   */
  private void clearNullValue() {
    if (valueTypeCase_ == 11) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int BOOLEAN_VALUE_FIELD_NUMBER = 1;
  /**
   * <pre>
   * A boolean value.
   * </pre>
   *
   * <code>bool boolean_value = 1;</code>
   * @return Whether the booleanValue field is set.
   */
  @java.lang.Override
  public boolean hasBooleanValue() {
    return valueTypeCase_ == 1;
  }
  /**
   * <pre>
   * A boolean value.
   * </pre>
   *
   * <code>bool boolean_value = 1;</code>
   * @return The booleanValue.
   */
  @java.lang.Override
  public boolean getBooleanValue() {
    if (valueTypeCase_ == 1) {
      return (java.lang.Boolean) valueType_;
    }
    return false;
  }
  /**
   * <pre>
   * A boolean value.
   * </pre>
   *
   * <code>bool boolean_value = 1;</code>
   * @param value The booleanValue to set.
   */
  private void setBooleanValue(boolean value) {
    valueTypeCase_ = 1;
    valueType_ = value;
  }
  /**
   * <pre>
   * A boolean value.
   * </pre>
   *
   * <code>bool boolean_value = 1;</code>
   */
  private void clearBooleanValue() {
    if (valueTypeCase_ == 1) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int INTEGER_VALUE_FIELD_NUMBER = 2;
  /**
   * <pre>
   * An integer value.
   * </pre>
   *
   * <code>int64 integer_value = 2;</code>
   * @return Whether the integerValue field is set.
   */
  @java.lang.Override
  public boolean hasIntegerValue() {
    return valueTypeCase_ == 2;
  }
  /**
   * <pre>
   * An integer value.
   * </pre>
   *
   * <code>int64 integer_value = 2;</code>
   * @return The integerValue.
   */
  @java.lang.Override
  public long getIntegerValue() {
    if (valueTypeCase_ == 2) {
      return (java.lang.Long) valueType_;
    }
    return 0L;
  }
  /**
   * <pre>
   * An integer value.
   * </pre>
   *
   * <code>int64 integer_value = 2;</code>
   * @param value The integerValue to set.
   */
  private void setIntegerValue(long value) {
    valueTypeCase_ = 2;
    valueType_ = value;
  }
  /**
   * <pre>
   * An integer value.
   * </pre>
   *
   * <code>int64 integer_value = 2;</code>
   */
  private void clearIntegerValue() {
    if (valueTypeCase_ == 2) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int DOUBLE_VALUE_FIELD_NUMBER = 3;
  /**
   * <pre>
   * A double value.
   * </pre>
   *
   * <code>double double_value = 3;</code>
   * @return Whether the doubleValue field is set.
   */
  @java.lang.Override
  public boolean hasDoubleValue() {
    return valueTypeCase_ == 3;
  }
  /**
   * <pre>
   * A double value.
   * </pre>
   *
   * <code>double double_value = 3;</code>
   * @return The doubleValue.
   */
  @java.lang.Override
  public double getDoubleValue() {
    if (valueTypeCase_ == 3) {
      return (java.lang.Double) valueType_;
    }
    return 0D;
  }
  /**
   * <pre>
   * A double value.
   * </pre>
   *
   * <code>double double_value = 3;</code>
   * @param value The doubleValue to set.
   */
  private void setDoubleValue(double value) {
    valueTypeCase_ = 3;
    valueType_ = value;
  }
  /**
   * <pre>
   * A double value.
   * </pre>
   *
   * <code>double double_value = 3;</code>
   */
  private void clearDoubleValue() {
    if (valueTypeCase_ == 3) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int TIMESTAMP_VALUE_FIELD_NUMBER = 10;
  /**
   * <pre>
   * A timestamp value.
   * Precise only to microseconds. When stored, any additional precision is
   * rounded down.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
   */
  @java.lang.Override
  public boolean hasTimestampValue() {
    return valueTypeCase_ == 10;
  }
  /**
   * <pre>
   * A timestamp value.
   * Precise only to microseconds. When stored, any additional precision is
   * rounded down.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestampValue() {
    if (valueTypeCase_ == 10) {
       return (com.google.protobuf.Timestamp) valueType_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <pre>
   * A timestamp value.
   * Precise only to microseconds. When stored, any additional precision is
   * rounded down.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
   */
  private void setTimestampValue(com.google.protobuf.Timestamp value) {
    value.getClass();
  valueType_ = value;
    valueTypeCase_ = 10;
  }
  /**
   * <pre>
   * A timestamp value.
   * Precise only to microseconds. When stored, any additional precision is
   * rounded down.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
   */
  private void mergeTimestampValue(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (valueTypeCase_ == 10 &&
        valueType_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      valueType_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) valueType_)
          .mergeFrom(value).buildPartial();
    } else {
      valueType_ = value;
    }
    valueTypeCase_ = 10;
  }
  /**
   * <pre>
   * A timestamp value.
   * Precise only to microseconds. When stored, any additional precision is
   * rounded down.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
   */
  private void clearTimestampValue() {
    if (valueTypeCase_ == 10) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 17;
  /**
   * <pre>
   * A string value.
   * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes of the UTF-8 representation are considered by
   * queries.
   * </pre>
   *
   * <code>string string_value = 17;</code>
   * @return Whether the stringValue field is set.
   */
  @java.lang.Override
  public boolean hasStringValue() {
    return valueTypeCase_ == 17;
  }
  /**
   * <pre>
   * A string value.
   * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes of the UTF-8 representation are considered by
   * queries.
   * </pre>
   *
   * <code>string string_value = 17;</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public java.lang.String getStringValue() {
    java.lang.String ref = "";
    if (valueTypeCase_ == 17) {
      ref = (java.lang.String) valueType_;
    }
    return ref;
  }
  /**
   * <pre>
   * A string value.
   * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes of the UTF-8 representation are considered by
   * queries.
   * </pre>
   *
   * <code>string string_value = 17;</code>
   * @return The bytes for stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.String ref = "";
    if (valueTypeCase_ == 17) {
      ref = (java.lang.String) valueType_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <pre>
   * A string value.
   * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes of the UTF-8 representation are considered by
   * queries.
   * </pre>
   *
   * <code>string string_value = 17;</code>
   * @param value The stringValue to set.
   */
  private void setStringValue(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  valueTypeCase_ = 17;
    valueType_ = value;
  }
  /**
   * <pre>
   * A string value.
   * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes of the UTF-8 representation are considered by
   * queries.
   * </pre>
   *
   * <code>string string_value = 17;</code>
   */
  private void clearStringValue() {
    if (valueTypeCase_ == 17) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }
  /**
   * <pre>
   * A string value.
   * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes of the UTF-8 representation are considered by
   * queries.
   * </pre>
   *
   * <code>string string_value = 17;</code>
   * @param value The bytes for stringValue to set.
   */
  private void setStringValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    valueType_ = value.toStringUtf8();
    valueTypeCase_ = 17;
  }

  public static final int BYTES_VALUE_FIELD_NUMBER = 18;
  /**
   * <pre>
   * A bytes value.
   * Must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes are considered by queries.
   * </pre>
   *
   * <code>bytes bytes_value = 18;</code>
   * @return Whether the bytesValue field is set.
   */
  @java.lang.Override
  public boolean hasBytesValue() {
    return valueTypeCase_ == 18;
  }
  /**
   * <pre>
   * A bytes value.
   * Must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes are considered by queries.
   * </pre>
   *
   * <code>bytes bytes_value = 18;</code>
   * @return The bytesValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesValue() {
    if (valueTypeCase_ == 18) {
      return (com.google.protobuf.ByteString) valueType_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }
  /**
   * <pre>
   * A bytes value.
   * Must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes are considered by queries.
   * </pre>
   *
   * <code>bytes bytes_value = 18;</code>
   * @param value The bytesValue to set.
   */
  private void setBytesValue(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  valueTypeCase_ = 18;
    valueType_ = value;
  }
  /**
   * <pre>
   * A bytes value.
   * Must not exceed 1 MiB - 89 bytes.
   * Only the first 1,500 bytes are considered by queries.
   * </pre>
   *
   * <code>bytes bytes_value = 18;</code>
   */
  private void clearBytesValue() {
    if (valueTypeCase_ == 18) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int REFERENCE_VALUE_FIELD_NUMBER = 5;
  /**
   * <pre>
   * A reference to a document. For example:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
   * </pre>
   *
   * <code>string reference_value = 5;</code>
   * @return Whether the referenceValue field is set.
   */
  @java.lang.Override
  public boolean hasReferenceValue() {
    return valueTypeCase_ == 5;
  }
  /**
   * <pre>
   * A reference to a document. For example:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
   * </pre>
   *
   * <code>string reference_value = 5;</code>
   * @return The referenceValue.
   */
  @java.lang.Override
  public java.lang.String getReferenceValue() {
    java.lang.String ref = "";
    if (valueTypeCase_ == 5) {
      ref = (java.lang.String) valueType_;
    }
    return ref;
  }
  /**
   * <pre>
   * A reference to a document. For example:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
   * </pre>
   *
   * <code>string reference_value = 5;</code>
   * @return The bytes for referenceValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceValueBytes() {
    java.lang.String ref = "";
    if (valueTypeCase_ == 5) {
      ref = (java.lang.String) valueType_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <pre>
   * A reference to a document. For example:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
   * </pre>
   *
   * <code>string reference_value = 5;</code>
   * @param value The referenceValue to set.
   */
  private void setReferenceValue(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  valueTypeCase_ = 5;
    valueType_ = value;
  }
  /**
   * <pre>
   * A reference to a document. For example:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
   * </pre>
   *
   * <code>string reference_value = 5;</code>
   */
  private void clearReferenceValue() {
    if (valueTypeCase_ == 5) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }
  /**
   * <pre>
   * A reference to a document. For example:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
   * </pre>
   *
   * <code>string reference_value = 5;</code>
   * @param value The bytes for referenceValue to set.
   */
  private void setReferenceValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    valueType_ = value.toStringUtf8();
    valueTypeCase_ = 5;
  }

  public static final int GEO_POINT_VALUE_FIELD_NUMBER = 8;
  /**
   * <pre>
   * A geo point value representing a point on the surface of Earth.
   * </pre>
   *
   * <code>.google.type.LatLng geo_point_value = 8;</code>
   */
  @java.lang.Override
  public boolean hasGeoPointValue() {
    return valueTypeCase_ == 8;
  }
  /**
   * <pre>
   * A geo point value representing a point on the surface of Earth.
   * </pre>
   *
   * <code>.google.type.LatLng geo_point_value = 8;</code>
   */
  @java.lang.Override
  public com.google.type.LatLng getGeoPointValue() {
    if (valueTypeCase_ == 8) {
       return (com.google.type.LatLng) valueType_;
    }
    return com.google.type.LatLng.getDefaultInstance();
  }
  /**
   * <pre>
   * A geo point value representing a point on the surface of Earth.
   * </pre>
   *
   * <code>.google.type.LatLng geo_point_value = 8;</code>
   */
  private void setGeoPointValue(com.google.type.LatLng value) {
    value.getClass();
  valueType_ = value;
    valueTypeCase_ = 8;
  }
  /**
   * <pre>
   * A geo point value representing a point on the surface of Earth.
   * </pre>
   *
   * <code>.google.type.LatLng geo_point_value = 8;</code>
   */
  private void mergeGeoPointValue(com.google.type.LatLng value) {
    value.getClass();
  if (valueTypeCase_ == 8 &&
        valueType_ != com.google.type.LatLng.getDefaultInstance()) {
      valueType_ = com.google.type.LatLng.newBuilder((com.google.type.LatLng) valueType_)
          .mergeFrom(value).buildPartial();
    } else {
      valueType_ = value;
    }
    valueTypeCase_ = 8;
  }
  /**
   * <pre>
   * A geo point value representing a point on the surface of Earth.
   * </pre>
   *
   * <code>.google.type.LatLng geo_point_value = 8;</code>
   */
  private void clearGeoPointValue() {
    if (valueTypeCase_ == 8) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int ARRAY_VALUE_FIELD_NUMBER = 9;
  /**
   * <pre>
   * An array value.
   * Cannot directly contain another array value, though can contain an
   * map which contains another array.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
   */
  @java.lang.Override
  public boolean hasArrayValue() {
    return valueTypeCase_ == 9;
  }
  /**
   * <pre>
   * An array value.
   * Cannot directly contain another array value, though can contain an
   * map which contains another array.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
   */
  @java.lang.Override
  public google.events.cloud.firestore.v1.ArrayValue getArrayValue() {
    if (valueTypeCase_ == 9) {
       return (google.events.cloud.firestore.v1.ArrayValue) valueType_;
    }
    return google.events.cloud.firestore.v1.ArrayValue.getDefaultInstance();
  }
  /**
   * <pre>
   * An array value.
   * Cannot directly contain another array value, though can contain an
   * map which contains another array.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
   */
  private void setArrayValue(google.events.cloud.firestore.v1.ArrayValue value) {
    value.getClass();
  valueType_ = value;
    valueTypeCase_ = 9;
  }
  /**
   * <pre>
   * An array value.
   * Cannot directly contain another array value, though can contain an
   * map which contains another array.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
   */
  private void mergeArrayValue(google.events.cloud.firestore.v1.ArrayValue value) {
    value.getClass();
  if (valueTypeCase_ == 9 &&
        valueType_ != google.events.cloud.firestore.v1.ArrayValue.getDefaultInstance()) {
      valueType_ = google.events.cloud.firestore.v1.ArrayValue.newBuilder((google.events.cloud.firestore.v1.ArrayValue) valueType_)
          .mergeFrom(value).buildPartial();
    } else {
      valueType_ = value;
    }
    valueTypeCase_ = 9;
  }
  /**
   * <pre>
   * An array value.
   * Cannot directly contain another array value, though can contain an
   * map which contains another array.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
   */
  private void clearArrayValue() {
    if (valueTypeCase_ == 9) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static final int MAP_VALUE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * A map value.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
   */
  @java.lang.Override
  public boolean hasMapValue() {
    return valueTypeCase_ == 6;
  }
  /**
   * <pre>
   * A map value.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
   */
  @java.lang.Override
  public google.events.cloud.firestore.v1.MapValue getMapValue() {
    if (valueTypeCase_ == 6) {
       return (google.events.cloud.firestore.v1.MapValue) valueType_;
    }
    return google.events.cloud.firestore.v1.MapValue.getDefaultInstance();
  }
  /**
   * <pre>
   * A map value.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
   */
  private void setMapValue(google.events.cloud.firestore.v1.MapValue value) {
    value.getClass();
  valueType_ = value;
    valueTypeCase_ = 6;
  }
  /**
   * <pre>
   * A map value.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
   */
  private void mergeMapValue(google.events.cloud.firestore.v1.MapValue value) {
    value.getClass();
  if (valueTypeCase_ == 6 &&
        valueType_ != google.events.cloud.firestore.v1.MapValue.getDefaultInstance()) {
      valueType_ = google.events.cloud.firestore.v1.MapValue.newBuilder((google.events.cloud.firestore.v1.MapValue) valueType_)
          .mergeFrom(value).buildPartial();
    } else {
      valueType_ = value;
    }
    valueTypeCase_ = 6;
  }
  /**
   * <pre>
   * A map value.
   * </pre>
   *
   * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
   */
  private void clearMapValue() {
    if (valueTypeCase_ == 6) {
      valueTypeCase_ = 0;
      valueType_ = null;
    }
  }

  public static google.events.cloud.firestore.v1.Value parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.firestore.v1.Value parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.firestore.v1.Value parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.cloud.firestore.v1.Value parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.events.cloud.firestore.v1.Value prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A message that can hold any of the supported value types.
   * </pre>
   *
   * Protobuf type {@code google.events.cloud.firestore.v1.Value}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.events.cloud.firestore.v1.Value, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.cloud.firestore.v1.Value)
      google.events.cloud.firestore.v1.ValueOrBuilder {
    // Construct using google.events.cloud.firestore.v1.Value.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ValueTypeCase
        getValueTypeCase() {
      return instance.getValueTypeCase();
    }

    public Builder clearValueType() {
      copyOnWrite();
      instance.clearValueType();
      return this;
    }


    /**
     * <pre>
     * A null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 11;</code>
     * @return Whether the nullValue field is set.
     */
    @java.lang.Override
    public boolean hasNullValue() {
      return instance.hasNullValue();
    }
    /**
     * <pre>
     * A null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 11;</code>
     * @return The enum numeric value on the wire for nullValue.
     */
    @java.lang.Override
    public int getNullValueValue() {
      return instance.getNullValueValue();
    }
    /**
     * <pre>
     * A null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 11;</code>
     * @param value The enum numeric value on the wire for nullValue to set.
     * @return This builder for chaining.
     */
    public Builder setNullValueValue(int value) {
      copyOnWrite();
      instance.setNullValueValue(value);
      return this;
    }
    /**
     * <pre>
     * A null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 11;</code>
     * @return The nullValue.
     */
    @java.lang.Override
    public com.google.protobuf.NullValue getNullValue() {
      return instance.getNullValue();
    }
    /**
     * <pre>
     * A null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 11;</code>
     * @param value The nullValue to set.
     * @return This builder for chaining.
     */
    public Builder setNullValue(com.google.protobuf.NullValue value) {
      copyOnWrite();
      instance.setNullValue(value);
      return this;
    }
    /**
     * <pre>
     * A null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearNullValue() {
      copyOnWrite();
      instance.clearNullValue();
      return this;
    }

    /**
     * <pre>
     * A boolean value.
     * </pre>
     *
     * <code>bool boolean_value = 1;</code>
     * @return Whether the booleanValue field is set.
     */
    @java.lang.Override
    public boolean hasBooleanValue() {
      return instance.hasBooleanValue();
    }
    /**
     * <pre>
     * A boolean value.
     * </pre>
     *
     * <code>bool boolean_value = 1;</code>
     * @return The booleanValue.
     */
    @java.lang.Override
    public boolean getBooleanValue() {
      return instance.getBooleanValue();
    }
    /**
     * <pre>
     * A boolean value.
     * </pre>
     *
     * <code>bool boolean_value = 1;</code>
     * @param value The booleanValue to set.
     * @return This builder for chaining.
     */
    public Builder setBooleanValue(boolean value) {
      copyOnWrite();
      instance.setBooleanValue(value);
      return this;
    }
    /**
     * <pre>
     * A boolean value.
     * </pre>
     *
     * <code>bool boolean_value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBooleanValue() {
      copyOnWrite();
      instance.clearBooleanValue();
      return this;
    }

    /**
     * <pre>
     * An integer value.
     * </pre>
     *
     * <code>int64 integer_value = 2;</code>
     * @return Whether the integerValue field is set.
     */
    @java.lang.Override
    public boolean hasIntegerValue() {
      return instance.hasIntegerValue();
    }
    /**
     * <pre>
     * An integer value.
     * </pre>
     *
     * <code>int64 integer_value = 2;</code>
     * @return The integerValue.
     */
    @java.lang.Override
    public long getIntegerValue() {
      return instance.getIntegerValue();
    }
    /**
     * <pre>
     * An integer value.
     * </pre>
     *
     * <code>int64 integer_value = 2;</code>
     * @param value The integerValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntegerValue(long value) {
      copyOnWrite();
      instance.setIntegerValue(value);
      return this;
    }
    /**
     * <pre>
     * An integer value.
     * </pre>
     *
     * <code>int64 integer_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntegerValue() {
      copyOnWrite();
      instance.clearIntegerValue();
      return this;
    }

    /**
     * <pre>
     * A double value.
     * </pre>
     *
     * <code>double double_value = 3;</code>
     * @return Whether the doubleValue field is set.
     */
    @java.lang.Override
    public boolean hasDoubleValue() {
      return instance.hasDoubleValue();
    }
    /**
     * <pre>
     * A double value.
     * </pre>
     *
     * <code>double double_value = 3;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      return instance.getDoubleValue();
    }
    /**
     * <pre>
     * A double value.
     * </pre>
     *
     * <code>double double_value = 3;</code>
     * @param value The doubleValue to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleValue(double value) {
      copyOnWrite();
      instance.setDoubleValue(value);
      return this;
    }
    /**
     * <pre>
     * A double value.
     * </pre>
     *
     * <code>double double_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleValue() {
      copyOnWrite();
      instance.clearDoubleValue();
      return this;
    }

    /**
     * <pre>
     * A timestamp value.
     * Precise only to microseconds. When stored, any additional precision is
     * rounded down.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
     */
    @java.lang.Override
    public boolean hasTimestampValue() {
      return instance.hasTimestampValue();
    }
    /**
     * <pre>
     * A timestamp value.
     * Precise only to microseconds. When stored, any additional precision is
     * rounded down.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestampValue() {
      return instance.getTimestampValue();
    }
    /**
     * <pre>
     * A timestamp value.
     * Precise only to microseconds. When stored, any additional precision is
     * rounded down.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
     */
    public Builder setTimestampValue(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setTimestampValue(value);
      return this;
    }
    /**
     * <pre>
     * A timestamp value.
     * Precise only to microseconds. When stored, any additional precision is
     * rounded down.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
     */
    public Builder setTimestampValue(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setTimestampValue(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A timestamp value.
     * Precise only to microseconds. When stored, any additional precision is
     * rounded down.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
     */
    public Builder mergeTimestampValue(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeTimestampValue(value);
      return this;
    }
    /**
     * <pre>
     * A timestamp value.
     * Precise only to microseconds. When stored, any additional precision is
     * rounded down.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp_value = 10;</code>
     */
    public Builder clearTimestampValue() {
      copyOnWrite();
      instance.clearTimestampValue();
      return this;
    }

    /**
     * <pre>
     * A string value.
     * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes of the UTF-8 representation are considered by
     * queries.
     * </pre>
     *
     * <code>string string_value = 17;</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return instance.hasStringValue();
    }
    /**
     * <pre>
     * A string value.
     * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes of the UTF-8 representation are considered by
     * queries.
     * </pre>
     *
     * <code>string string_value = 17;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      return instance.getStringValue();
    }
    /**
     * <pre>
     * A string value.
     * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes of the UTF-8 representation are considered by
     * queries.
     * </pre>
     *
     * <code>string string_value = 17;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      return instance.getStringValueBytes();
    }
    /**
     * <pre>
     * A string value.
     * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes of the UTF-8 representation are considered by
     * queries.
     * </pre>
     *
     * <code>string string_value = 17;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setStringValue(value);
      return this;
    }
    /**
     * <pre>
     * A string value.
     * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes of the UTF-8 representation are considered by
     * queries.
     * </pre>
     *
     * <code>string string_value = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      copyOnWrite();
      instance.clearStringValue();
      return this;
    }
    /**
     * <pre>
     * A string value.
     * The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes of the UTF-8 representation are considered by
     * queries.
     * </pre>
     *
     * <code>string string_value = 17;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStringValueBytes(value);
      return this;
    }

    /**
     * <pre>
     * A bytes value.
     * Must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes are considered by queries.
     * </pre>
     *
     * <code>bytes bytes_value = 18;</code>
     * @return Whether the bytesValue field is set.
     */
    @java.lang.Override
    public boolean hasBytesValue() {
      return instance.hasBytesValue();
    }
    /**
     * <pre>
     * A bytes value.
     * Must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes are considered by queries.
     * </pre>
     *
     * <code>bytes bytes_value = 18;</code>
     * @return The bytesValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesValue() {
      return instance.getBytesValue();
    }
    /**
     * <pre>
     * A bytes value.
     * Must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes are considered by queries.
     * </pre>
     *
     * <code>bytes bytes_value = 18;</code>
     * @param value The bytesValue to set.
     * @return This builder for chaining.
     */
    public Builder setBytesValue(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBytesValue(value);
      return this;
    }
    /**
     * <pre>
     * A bytes value.
     * Must not exceed 1 MiB - 89 bytes.
     * Only the first 1,500 bytes are considered by queries.
     * </pre>
     *
     * <code>bytes bytes_value = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesValue() {
      copyOnWrite();
      instance.clearBytesValue();
      return this;
    }

    /**
     * <pre>
     * A reference to a document. For example:
     * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
     * </pre>
     *
     * <code>string reference_value = 5;</code>
     * @return Whether the referenceValue field is set.
     */
    @java.lang.Override
    public boolean hasReferenceValue() {
      return instance.hasReferenceValue();
    }
    /**
     * <pre>
     * A reference to a document. For example:
     * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
     * </pre>
     *
     * <code>string reference_value = 5;</code>
     * @return The referenceValue.
     */
    @java.lang.Override
    public java.lang.String getReferenceValue() {
      return instance.getReferenceValue();
    }
    /**
     * <pre>
     * A reference to a document. For example:
     * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
     * </pre>
     *
     * <code>string reference_value = 5;</code>
     * @return The bytes for referenceValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReferenceValueBytes() {
      return instance.getReferenceValueBytes();
    }
    /**
     * <pre>
     * A reference to a document. For example:
     * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
     * </pre>
     *
     * <code>string reference_value = 5;</code>
     * @param value The referenceValue to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setReferenceValue(value);
      return this;
    }
    /**
     * <pre>
     * A reference to a document. For example:
     * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
     * </pre>
     *
     * <code>string reference_value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceValue() {
      copyOnWrite();
      instance.clearReferenceValue();
      return this;
    }
    /**
     * <pre>
     * A reference to a document. For example:
     * `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
     * </pre>
     *
     * <code>string reference_value = 5;</code>
     * @param value The bytes for referenceValue to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReferenceValueBytes(value);
      return this;
    }

    /**
     * <pre>
     * A geo point value representing a point on the surface of Earth.
     * </pre>
     *
     * <code>.google.type.LatLng geo_point_value = 8;</code>
     */
    @java.lang.Override
    public boolean hasGeoPointValue() {
      return instance.hasGeoPointValue();
    }
    /**
     * <pre>
     * A geo point value representing a point on the surface of Earth.
     * </pre>
     *
     * <code>.google.type.LatLng geo_point_value = 8;</code>
     */
    @java.lang.Override
    public com.google.type.LatLng getGeoPointValue() {
      return instance.getGeoPointValue();
    }
    /**
     * <pre>
     * A geo point value representing a point on the surface of Earth.
     * </pre>
     *
     * <code>.google.type.LatLng geo_point_value = 8;</code>
     */
    public Builder setGeoPointValue(com.google.type.LatLng value) {
      copyOnWrite();
      instance.setGeoPointValue(value);
      return this;
    }
    /**
     * <pre>
     * A geo point value representing a point on the surface of Earth.
     * </pre>
     *
     * <code>.google.type.LatLng geo_point_value = 8;</code>
     */
    public Builder setGeoPointValue(
        com.google.type.LatLng.Builder builderForValue) {
      copyOnWrite();
      instance.setGeoPointValue(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A geo point value representing a point on the surface of Earth.
     * </pre>
     *
     * <code>.google.type.LatLng geo_point_value = 8;</code>
     */
    public Builder mergeGeoPointValue(com.google.type.LatLng value) {
      copyOnWrite();
      instance.mergeGeoPointValue(value);
      return this;
    }
    /**
     * <pre>
     * A geo point value representing a point on the surface of Earth.
     * </pre>
     *
     * <code>.google.type.LatLng geo_point_value = 8;</code>
     */
    public Builder clearGeoPointValue() {
      copyOnWrite();
      instance.clearGeoPointValue();
      return this;
    }

    /**
     * <pre>
     * An array value.
     * Cannot directly contain another array value, though can contain an
     * map which contains another array.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
     */
    @java.lang.Override
    public boolean hasArrayValue() {
      return instance.hasArrayValue();
    }
    /**
     * <pre>
     * An array value.
     * Cannot directly contain another array value, though can contain an
     * map which contains another array.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
     */
    @java.lang.Override
    public google.events.cloud.firestore.v1.ArrayValue getArrayValue() {
      return instance.getArrayValue();
    }
    /**
     * <pre>
     * An array value.
     * Cannot directly contain another array value, though can contain an
     * map which contains another array.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
     */
    public Builder setArrayValue(google.events.cloud.firestore.v1.ArrayValue value) {
      copyOnWrite();
      instance.setArrayValue(value);
      return this;
    }
    /**
     * <pre>
     * An array value.
     * Cannot directly contain another array value, though can contain an
     * map which contains another array.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
     */
    public Builder setArrayValue(
        google.events.cloud.firestore.v1.ArrayValue.Builder builderForValue) {
      copyOnWrite();
      instance.setArrayValue(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * An array value.
     * Cannot directly contain another array value, though can contain an
     * map which contains another array.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
     */
    public Builder mergeArrayValue(google.events.cloud.firestore.v1.ArrayValue value) {
      copyOnWrite();
      instance.mergeArrayValue(value);
      return this;
    }
    /**
     * <pre>
     * An array value.
     * Cannot directly contain another array value, though can contain an
     * map which contains another array.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.ArrayValue array_value = 9;</code>
     */
    public Builder clearArrayValue() {
      copyOnWrite();
      instance.clearArrayValue();
      return this;
    }

    /**
     * <pre>
     * A map value.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
     */
    @java.lang.Override
    public boolean hasMapValue() {
      return instance.hasMapValue();
    }
    /**
     * <pre>
     * A map value.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
     */
    @java.lang.Override
    public google.events.cloud.firestore.v1.MapValue getMapValue() {
      return instance.getMapValue();
    }
    /**
     * <pre>
     * A map value.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
     */
    public Builder setMapValue(google.events.cloud.firestore.v1.MapValue value) {
      copyOnWrite();
      instance.setMapValue(value);
      return this;
    }
    /**
     * <pre>
     * A map value.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
     */
    public Builder setMapValue(
        google.events.cloud.firestore.v1.MapValue.Builder builderForValue) {
      copyOnWrite();
      instance.setMapValue(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A map value.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
     */
    public Builder mergeMapValue(google.events.cloud.firestore.v1.MapValue value) {
      copyOnWrite();
      instance.mergeMapValue(value);
      return this;
    }
    /**
     * <pre>
     * A map value.
     * </pre>
     *
     * <code>.google.events.cloud.firestore.v1.MapValue map_value = 6;</code>
     */
    public Builder clearMapValue() {
      copyOnWrite();
      instance.clearMapValue();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.events.cloud.firestore.v1.Value)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.events.cloud.firestore.v1.Value();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "valueType_",
            "valueTypeCase_",
            google.events.cloud.firestore.v1.MapValue.class,
            com.google.type.LatLng.class,
            google.events.cloud.firestore.v1.ArrayValue.class,
            com.google.protobuf.Timestamp.class,
          };
          java.lang.String info =
              "\u0000\u000b\u0001\u0000\u0001\u0012\u000b\u0000\u0000\u0000\u0001:\u0000\u00025" +
              "\u0000\u00033\u0000\u0005\u023b\u0000\u0006<\u0000\b<\u0000\t<\u0000\n<\u0000\u000b" +
              "?\u0000\u0011\u023b\u0000\u0012=\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.events.cloud.firestore.v1.Value> parser = PARSER;
        if (parser == null) {
          synchronized (google.events.cloud.firestore.v1.Value.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.events.cloud.firestore.v1.Value>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.events.cloud.firestore.v1.Value)
  private static final google.events.cloud.firestore.v1.Value DEFAULT_INSTANCE;
  static {
    Value defaultInstance = new Value();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Value.class, defaultInstance);
  }

  public static google.events.cloud.firestore.v1.Value getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Value> PARSER;

  public static com.google.protobuf.Parser<Value> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

