// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/database/v1/data.proto

package google.events.firebase.database.v1;

/**
 * <pre>
 * The data within all Firebase Real Time Database reference events.
 * </pre>
 *
 * Protobuf type {@code google.events.firebase.database.v1.ReferenceEventData}
 */
public  final class ReferenceEventData extends
    com.google.protobuf.GeneratedMessageLite<
        ReferenceEventData, ReferenceEventData.Builder> implements
    // @@protoc_insertion_point(message_implements:google.events.firebase.database.v1.ReferenceEventData)
    ReferenceEventDataOrBuilder {
  private ReferenceEventData() {
  }
  public static final int DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.Value data_;
  /**
   * <pre>
   * The original data for the reference.
   * </pre>
   *
   * <code>.google.protobuf.Value data = 1;</code>
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <pre>
   * The original data for the reference.
   * </pre>
   *
   * <code>.google.protobuf.Value data = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Value getData() {
    return data_ == null ? com.google.protobuf.Value.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * The original data for the reference.
   * </pre>
   *
   * <code>.google.protobuf.Value data = 1;</code>
   */
  private void setData(com.google.protobuf.Value value) {
    value.getClass();
  data_ = value;
    
    }
  /**
   * <pre>
   * The original data for the reference.
   * </pre>
   *
   * <code>.google.protobuf.Value data = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeData(com.google.protobuf.Value value) {
    value.getClass();
  if (data_ != null &&
        data_ != com.google.protobuf.Value.getDefaultInstance()) {
      data_ =
        com.google.protobuf.Value.newBuilder(data_).mergeFrom(value).buildPartial();
    } else {
      data_ = value;
    }
    
  }
  /**
   * <pre>
   * The original data for the reference.
   * </pre>
   *
   * <code>.google.protobuf.Value data = 1;</code>
   */
  private void clearData() {  data_ = null;
    
  }

  public static final int DELTA_FIELD_NUMBER = 2;
  private com.google.protobuf.Value delta_;
  /**
   * <pre>
   * The change in the reference data.
   * </pre>
   *
   * <code>.google.protobuf.Value delta = 2;</code>
   */
  @java.lang.Override
  public boolean hasDelta() {
    return delta_ != null;
  }
  /**
   * <pre>
   * The change in the reference data.
   * </pre>
   *
   * <code>.google.protobuf.Value delta = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Value getDelta() {
    return delta_ == null ? com.google.protobuf.Value.getDefaultInstance() : delta_;
  }
  /**
   * <pre>
   * The change in the reference data.
   * </pre>
   *
   * <code>.google.protobuf.Value delta = 2;</code>
   */
  private void setDelta(com.google.protobuf.Value value) {
    value.getClass();
  delta_ = value;
    
    }
  /**
   * <pre>
   * The change in the reference data.
   * </pre>
   *
   * <code>.google.protobuf.Value delta = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDelta(com.google.protobuf.Value value) {
    value.getClass();
  if (delta_ != null &&
        delta_ != com.google.protobuf.Value.getDefaultInstance()) {
      delta_ =
        com.google.protobuf.Value.newBuilder(delta_).mergeFrom(value).buildPartial();
    } else {
      delta_ = value;
    }
    
  }
  /**
   * <pre>
   * The change in the reference data.
   * </pre>
   *
   * <code>.google.protobuf.Value delta = 2;</code>
   */
  private void clearDelta() {  delta_ = null;
    
  }

  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.events.firebase.database.v1.ReferenceEventData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.events.firebase.database.v1.ReferenceEventData prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The data within all Firebase Real Time Database reference events.
   * </pre>
   *
   * Protobuf type {@code google.events.firebase.database.v1.ReferenceEventData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.events.firebase.database.v1.ReferenceEventData, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.firebase.database.v1.ReferenceEventData)
      google.events.firebase.database.v1.ReferenceEventDataOrBuilder {
    // Construct using google.events.firebase.database.v1.ReferenceEventData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The original data for the reference.
     * </pre>
     *
     * <code>.google.protobuf.Value data = 1;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return instance.hasData();
    }
    /**
     * <pre>
     * The original data for the reference.
     * </pre>
     *
     * <code>.google.protobuf.Value data = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getData() {
      return instance.getData();
    }
    /**
     * <pre>
     * The original data for the reference.
     * </pre>
     *
     * <code>.google.protobuf.Value data = 1;</code>
     */
    public Builder setData(com.google.protobuf.Value value) {
      copyOnWrite();
      instance.setData(value);
      return this;
      }
    /**
     * <pre>
     * The original data for the reference.
     * </pre>
     *
     * <code>.google.protobuf.Value data = 1;</code>
     */
    public Builder setData(
        com.google.protobuf.Value.Builder builderForValue) {
      copyOnWrite();
      instance.setData(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The original data for the reference.
     * </pre>
     *
     * <code>.google.protobuf.Value data = 1;</code>
     */
    public Builder mergeData(com.google.protobuf.Value value) {
      copyOnWrite();
      instance.mergeData(value);
      return this;
    }
    /**
     * <pre>
     * The original data for the reference.
     * </pre>
     *
     * <code>.google.protobuf.Value data = 1;</code>
     */
    public Builder clearData() {  copyOnWrite();
      instance.clearData();
      return this;
    }

    /**
     * <pre>
     * The change in the reference data.
     * </pre>
     *
     * <code>.google.protobuf.Value delta = 2;</code>
     */
    @java.lang.Override
    public boolean hasDelta() {
      return instance.hasDelta();
    }
    /**
     * <pre>
     * The change in the reference data.
     * </pre>
     *
     * <code>.google.protobuf.Value delta = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getDelta() {
      return instance.getDelta();
    }
    /**
     * <pre>
     * The change in the reference data.
     * </pre>
     *
     * <code>.google.protobuf.Value delta = 2;</code>
     */
    public Builder setDelta(com.google.protobuf.Value value) {
      copyOnWrite();
      instance.setDelta(value);
      return this;
      }
    /**
     * <pre>
     * The change in the reference data.
     * </pre>
     *
     * <code>.google.protobuf.Value delta = 2;</code>
     */
    public Builder setDelta(
        com.google.protobuf.Value.Builder builderForValue) {
      copyOnWrite();
      instance.setDelta(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The change in the reference data.
     * </pre>
     *
     * <code>.google.protobuf.Value delta = 2;</code>
     */
    public Builder mergeDelta(com.google.protobuf.Value value) {
      copyOnWrite();
      instance.mergeDelta(value);
      return this;
    }
    /**
     * <pre>
     * The change in the reference data.
     * </pre>
     *
     * <code>.google.protobuf.Value delta = 2;</code>
     */
    public Builder clearDelta() {  copyOnWrite();
      instance.clearDelta();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.events.firebase.database.v1.ReferenceEventData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.events.firebase.database.v1.ReferenceEventData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "data_",
            "delta_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\t\u0002\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.events.firebase.database.v1.ReferenceEventData> parser = PARSER;
        if (parser == null) {
          synchronized (google.events.firebase.database.v1.ReferenceEventData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.events.firebase.database.v1.ReferenceEventData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.events.firebase.database.v1.ReferenceEventData)
  private static final google.events.firebase.database.v1.ReferenceEventData DEFAULT_INSTANCE;
  static {
    ReferenceEventData defaultInstance = new ReferenceEventData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ReferenceEventData.class, defaultInstance);
  }

  public static google.events.firebase.database.v1.ReferenceEventData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ReferenceEventData> PARSER;

  public static com.google.protobuf.Parser<ReferenceEventData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

